table Inventory_Levels
	lineageTag: 00ce2257-1d01-4759-b515-2b943ee06eb3

	column sku
		dataType: string
		lineageTag: 2e8026b1-6afb-4167-9de8-35ecb089099a
		summarizeBy: none
		sourceColumn: sku

	column warehouse
		dataType: string
		lineageTag: 40fc1e87-abe7-48d7-8fa2-86263de3d1ec
		summarizeBy: none
		sourceColumn: warehouse

	column qty_on_hand
		dataType: int64
		lineageTag: e53ab748-38ce-47b9-ba0c-324a98cb7f4e
		summarizeBy: sum
		sourceColumn: qty_on_hand

	column reorder_point
		dataType: int64
		lineageTag: 0e06a90f-9271-42ef-a3d0-8166382d9261
		summarizeBy: sum
		sourceColumn: reorder_point

	partition Inventory_Levels = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Data\Supply\inventory_levels.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
