table GL_Transactions
	lineageTag: 979fc340-7d22-4bec-9793-7e88cffcd4da

	column txn_id
		dataType: string
		lineageTag: bf5b278b-da8f-454a-a034-028ecef9fdcb
		summarizeBy: none
		sourceColumn: txn_id

	column account
		dataType: string
		lineageTag: 9e357da9-9e55-4cb5-bf86-4e226b757791
		summarizeBy: none
		sourceColumn: account

	column amount
		dataType: decimal
		lineageTag: d59f3be4-9cd7-4555-8c2d-47966cd0cb03
		summarizeBy: sum
		sourceColumn: amount

	column date
		dataType: string
		lineageTag: b5933fad-3592-44a7-92bc-2b60a5859410
		summarizeBy: none
		sourceColumn: date

	partition GL_Transactions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Finance\gl_transactions.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
