table Vendor_Payments
	lineageTag: 18946036-b755-4a52-a5a0-e04519f7acec

	column vendor_id
		dataType: string
		lineageTag: 328132f3-24b5-4623-99d0-1c9a1497bcf9
		summarizeBy: none
		sourceColumn: vendor_id

	column vendor_name
		dataType: string
		lineageTag: 023f5a3e-d5d7-4764-9972-9be674f8ddbd
		summarizeBy: none
		sourceColumn: vendor_name

	column amount
		dataType: decimal
		lineageTag: 2e8bb6ab-b8f5-4d8a-878f-5e85aeb9aa2e
		summarizeBy: sum
		sourceColumn: amount

	column paid_date
		dataType: string
		lineageTag: 138efa63-39c3-4c72-809d-d70e216fdf5c
		summarizeBy: none
		sourceColumn: paid_date

	partition Vendor_Payments = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Finance\vendor_payments.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
