table Main
	lineageTag: a1b2c3d4-1111-2222-3333-444455556666

	column id
		dataType: int64
		formatString: 0
		lineageTag: 11111111-aaaa-bbbb-cccc-ddddeeeeaaaa
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column oe_total_sales_price
		dataType: decimal
		lineageTag: 22222222-aaaa-bbbb-cccc-ddddeeeebbbb
		summarizeBy: sum
		sourceColumn: oe_total_sales_price

		annotation SummarizationSetBy = Automatic

	column oe_final_quantity
		dataType: int64
		formatString: 0
		lineageTag: 33333333-aaaa-bbbb-cccc-ddddeeeecccc
		summarizeBy: sum
		sourceColumn: oe_final_quantity

		annotation SummarizationSetBy = Automatic

	column Individual
		dataType: string
		lineageTag: 44444444-aaaa-bbbb-cccc-ddddeeeedddd
		summarizeBy: none
		sourceColumn: Individual

		annotation SummarizationSetBy = Automatic

	partition Main = m
		mode: import
		source =
				let
				    Source = Sql.Database("sqlserver01.company.local", "SalesDB"),
				    dbo_Orders = Source{[Schema="dbo",Item="Orders"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_Orders, each [Status] = "Active"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"id", Int64.Type}, {"oe_total_sales_price", Currency.Type}, {"oe_final_quantity", Int64.Type}, {"Individual", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
