table 'MP Plan'
	lineageTag: c3d4e5f6-3333-4444-5555-666677778888

	column Month
		dataType: string
		lineageTag: 77777777-aaaa-bbbb-cccc-ddddeeee3333
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: decimal
		lineageTag: 88888888-aaaa-bbbb-cccc-ddddeeee4444
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition 'MP Plan' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Plans\MP_Plan_2026.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type text}, {"Value", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
