import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={window:{},structuredClone,URL};vm.createContext(context);
vm.runInContext(fs.readFileSync('app/static/flow_recording_model.js','utf8'),context);
const M=context.window.RecordedFlowModel;
const click={id:'click',action:'click',page:'page',locator:[{method:'get_by_role',args:['button'],kwargs:{name:'Excel down'}}]};
const event={id:'event',action:'download',page:'page',steps:[click],output:{format:'xlsx'}};
assert.equal(M.describe(event),'Click “Excel down”');
assert.equal(M.triggering(event).id,'click');
const def={steps:[{id:'open',action:'goto',page:'page'},event,{id:'wait',action:'wait',page:'page',seconds:5}]};
const moved=M.move(def,'event',2);
assert.equal(moved.steps[2].id,'event');assert.equal(moved.steps[2].steps[0].id,'click');
assert.equal(def.steps[1].id,'event');
assert.throws(()=>M.move(def,'click',0),/unit/);
const popup={id:'popup',action:'popup',page:'page',result_page:'page1',steps:[structuredClone(click)]};
const use={id:'use',action:'click',page:'page1'};
const pages={steps:[popup,use]};M.validatePages(pages);
assert.throws(()=>M.move(pages,'use',0),/before/);
assert.throws(()=>M.remove(pages,'popup'),/before/);
const input={id:'input',action:'fill',page:'page',locator:[{method:'get_by_label',args:['Start'],kwargs:{exact:true}}]};
const owned={steps:[input,{...event,output:{period_checks:[{column:'Date',parameter:'start'}]}}],parameters:{start:{step_id:'input',mode:'fixed'},end:{step_id:'click',mode:'portal_default',not_after:'start'}},identity:{text:'Title',target:M.target(input)},readiness:{trigger_step_id:'input'}};
const removed=M.remove(owned,'input');
assert.equal(removed.parameters.start,undefined);assert.equal(removed.parameters.end.not_after,undefined);
assert.equal(removed.steps[0].output.period_checks.length,0);assert.equal(removed.identity.text,undefined);assert.equal(removed.readiness.trigger_step_id,undefined);
assert.equal(M.owner(def,'click').id,'event');
console.log('Visual recording model tests passed');

const title={text:'Sales Report',kind:'page_title',target:{page:'page',locator:[]}};
const waitTitle={steps:[{id:'wait',action:'wait',page:'page',seconds:5},{id:'open',action:'goto',page:'page'}],identity:title};
assert.equal(M.remove(waitTitle,'wait').identity.text,'Sales Report');
