import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync(new URL('../app/static/app.js', import.meta.url), 'utf8');
const controls = {};
const set = (id, value, rest = {}) => controls[`#${id}`] = {value, dataset: {}, ...rest};
for (const [id, value] of Object.entries({name:' Draft ', 'schedule-type':'manual', 'schedule-time':'09:15', 'schedule-day':'2', 'owner':'', 'sql-mode':'append', 'sql-database':'CaseDB', 'sql-schema':'CaseSchema', 'sql-table':'MyTable', 'local-file-path':' C:\\input.xlsx ', 'local-file-worksheet':' Exact Sheet ', 'outlook-subject':' Daily report ', site:'7', report:'9', 'period-strategy':'none', 'download-mode':'single', 'file-format':'csv_file_format', 'browser-mode':'headless', 'excel-trim':'none', filename:'{flow}_{export}.csv', 'start-week':'2026-W01', 'end-week':'2026-W05'})) set(`flow-${id}`,value);
set('flow-sql-enabled','',{checked:true}); set('flow-transform-enabled','',{checked:false}); set('flow-sql-uppercase','',{checked:true});
set('flow-export-report-title','',{checked:true,dataset:{inherit:'true'}}); set('flow-export-filter-details','',{checked:false,disabled:true});
const form = {dataset:{sourceType:'file',id:''}};
controls['#flow-builder-form'] = form;
const context = {$: id => controls[id], window:{_flowsState:{flows:[],catalog:{asap_download_types:[{key:'csv_file_format',file_format:'csv'}]}}}, document:{querySelectorAll: selector => selector.includes('export-view') ? [{value:'View A'}, {value:'View B'}] : []}, _flowSiteIsAsap: () => true};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function _flowCollectBuilder'),source.indexOf('function _pipelineDuration')),context);
let body = context._flowCollectBuilder();
assert.equal(body.name,'Draft'); assert.equal(body.local_file_worksheet,' Exact Sheet ');
assert.equal(body.target_folder,null); assert.equal(body.output_mode,'private_snapshot');
assert.equal(body.owner_person_id,null); assert.equal(body.enabled,false);
assert.equal(body.sql_database,'CaseDB'); assert.equal(body.sql_table,'MyTable'); assert.equal(body.sql_uppercase,true);
set('flow-local-file-path','C:\\input.csv'); assert.equal(context._flowCollectBuilder().local_file_worksheet,null);
form.dataset.sourceType = 'outlook'; body=context._flowCollectBuilder();
assert.equal(body.outlook_subject_contains,'Daily report'); assert.equal(body.filename_template,null); // server fixes original-name semantics
form.dataset.sourceType = 'portal'; body=context._flowCollectBuilder();
assert.deepEqual(Array.from(body.export_views),['View A','View B']);
assert.equal(body.export_report_title,null); assert.equal(body.export_filter_details,null);
assert.equal(body.period_strategy,'none'); assert.equal(body.start_week,null); assert.equal(body.end_week,null);
assert.equal(body.asap_download_type,'csv_file_format'); assert.equal(body.sql_schema,'CaseSchema');
set('flow-browser-mode', 'headed'); set('flow-download-parallelism', '3');
body = context._flowCollectBuilder();
assert.equal(body.browser_mode, 'headed'); assert.equal(body.download_parallelism, 3);
vm.runInContext(source.slice(source.indexOf('function _flowStepSummary'), source.indexOf('function _flowBuildSteps')),context);
const seen=[];
context._flowRevealStep = (_form,input) => seen.push(input);
const input={focus:()=>seen.push('focus')};
context._flowRevealServerError({querySelector:id=>id==='#flow-local-file-worksheet'?input:null}, {validation:[{loc:['body','local_file_worksheet'],msg:'Exact worksheet required'}]});
assert.deepEqual(seen,[input,'focus']);
assert.match(source,/queueMicrotask\(\(\) => \{ _flowRevealStep\(form, target\); target.focus\(\)/);
assert.match(source,/next.type = "button"/);
console.log('flow builder payload and error tests passed');
