import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync(new URL('../app/static/app.js', import.meta.url), 'utf8');
const code = source.slice(source.indexOf('function _flowListHtml'), source.indexOf('/** The folder a report sits in'));
const context = {window: {}, esc: v => String(v ?? '').replaceAll('<','&lt;').replaceAll('"','&quot;'), formatDate: v => v, timeAgo: v => v, _flowEmptyState: () => 'empty', _flowStatusBadge: v => String(v)};
vm.createContext(context); vm.runInContext(code, context);
const flows = [{id: 1, name: '<Local>', source_type: 'file', local_file_path: 'x', schedule_type: 'manual'}, {id: 2, name: 'ASAP', source_adapter: 'asap_portal', last_status: 'failed', sql_handoff_enabled: true, sql_database: 'Db', sql_schema: 'CaseSensitive', sql_table: 'MyTable'}, {id: 3, name: 'Other', source_type: 'portal'}];
let html = context._flowListHtml(flows, [], {}, [{flow_id: 1, status: 'running'}]);
assert(html.indexOf('> ASAP ') < html.indexOf('> Local '));
assert(html.indexOf('> Local ') < html.indexOf('> Web '));
assert(!html.includes('flow-group-GSCM'));
assert.match(html, /aria-expanded="false"/);
assert.match(html, /1 active runs/); assert.match(html, /1 failed/);
assert.match(html, /&lt;Local>/); assert.match(html, /Db.CaseSensitive.MyTable/);
assert.match(html, /Private snapshots/); assert(!html.includes('Freshness'));
for (const label of ['Flow','Source','Owner','Type','To','Schedule','Last run','Active','Actions']) assert(html.includes(`>${label}<`));
for (const cls of ['flow-run', 'flow-stop', 'flow-edit', 'flow-delete', 'flow-open-folder', 'flow-enabled-switch']) assert(html.includes(cls));
context.window._flowOpenGroupMemory = undefined;
context.sessionStorage = {getItem: () => '["Local","<script>"]'};
assert.deepEqual([...context._flowOpenGroups()], ['Local']);
html = context._flowListHtml(flows, [], {});
assert.match(html, /id="flow-group-rows-Local" >/);
context.window._flowOpenGroupMemory = undefined;
context.sessionStorage.getItem = () => '{';
assert.equal(context._flowOpenGroups().size, 0);
console.log('flow group tests passed');
