table Reorder_Points
	lineageTag: 6f70c2cf-659e-40d9-a63d-3c32eb0b768c

	column sku
		dataType: string
		lineageTag: 0ad2da75-9d07-455a-821e-23b1376678f7
		summarizeBy: none
		sourceColumn: sku

	column min_qty
		dataType: int64
		lineageTag: 909ec4f0-790c-42b2-a9c1-03b7cec71152
		summarizeBy: sum
		sourceColumn: min_qty

	column max_qty
		dataType: int64
		lineageTag: 26475f52-aa62-4244-9c59-0f6481d80587
		summarizeBy: sum
		sourceColumn: max_qty

	column lead_time
		dataType: int64
		lineageTag: 0dceb7b3-1836-454c-b804-304737c9d511
		summarizeBy: sum
		sourceColumn: lead_time

	partition Reorder_Points = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Inventory\reorder_points.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
