table Warehouse_Stock
	lineageTag: a450e168-3467-44c5-afc5-6ed8627ef440

	column sku
		dataType: string
		lineageTag: a5716843-ff85-41c6-aa53-ff3e54c0ef71
		summarizeBy: none
		sourceColumn: sku

	column warehouse
		dataType: string
		lineageTag: c09add06-0b00-4bfb-82b6-6b181cffd17d
		summarizeBy: none
		sourceColumn: warehouse

	column qty_on_hand
		dataType: int64
		lineageTag: 637bbfb3-0412-4aa1-95fe-d4f520cbe12a
		summarizeBy: sum
		sourceColumn: qty_on_hand

	column reorder_point
		dataType: int64
		lineageTag: 218e395f-c826-4488-9d03-0a060db65a8e
		summarizeBy: sum
		sourceColumn: reorder_point

	partition Warehouse_Stock = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Data\Supply\inventory_levels.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
