"""Exact, scoped GSCM Favorite-grid selection for recorded click steps.

This deliberately does not reopen GSCM, activate a tab, expand folders, or
press Go.  The recording owns all of those actions.  Native selection remains
disabled until a work-PC qualification is stored with a future target.
"""
from __future__ import annotations

import time

from app import flow_gscm

TARGET_KIND = "gscm_favorite"
CAPABILITY = "gscm_bookmark_targets_v1"
DEADLINE_SECONDS = 120


def is_target(step: dict) -> bool:
    return isinstance(step.get("bookmark_target"), dict) and step["bookmark_target"].get("kind") == TARGET_KIND


def validate_target(step: dict) -> None:
    target = step.get("bookmark_target")
    if target is None:
        return
    if not isinstance(target, dict) or target.get("kind") != TARGET_KIND:
        raise ValueError("Unsupported recorded target type.")
    if step.get("action") != "click":
        raise ValueError("A GSCM Favorite target must be a click step.")
    name = target.get("bookmark_name")
    if not isinstance(name, str) or not name.strip() or name != name.strip() or len(name) > 300:
        raise ValueError("GSCM Favorite targets require the exact bookmark name.")
    for key in ("bookmark_id", "scope"):
        value = target.get(key)
        if value is not None and (not isinstance(value, str) or not value.strip() or value != value.strip() or len(value) > 300):
            raise ValueError(f"Invalid GSCM Favorite {key}.")
    if target.get("native_strategy") is not None:
        raise ValueError("Native GSCM bookmark selection is not qualified on this worker.")


def _identity(page, target: dict) -> dict:
    """Resolve exactly one current-scope dataset identity; never use a row slot."""
    name = target["bookmark_name"]
    scope = target.get("scope")
    wanted_id = target.get("bookmark_id")
    entries = flow_gscm.bookmark_dataset_entries(page)
    if entries is None:
        raise RuntimeError("GSCM Favorite data is unavailable in the current frame.")
    matches = [entry for entry in entries if entry.get("identity_name") == name
               and (not scope or entry.get("tab") == scope)]
    if wanted_id:
        matches = [entry for entry in matches if entry.get("bookmark_id") == wanted_id]
    if not matches:
        raise RuntimeError(f"GSCM Favorite bookmark {name!r} is not in the current scope. Check the recorded folder/tab steps and repair the target.")
    if len(matches) != 1:
        raise RuntimeError(f"GSCM Favorite bookmark {name!r} is ambiguous in the current scope. Repair this target with its stable bookmark ID.")
    if not matches[0].get("bookmark_id"):
        raise RuntimeError(f"GSCM Favorite bookmark {name!r} has no stable identity. Re-record or repair this target.")
    return matches[0]


def _rendered_target(page, name: str):
    rows = [(root, row) for root, row in flow_gscm.favorite_tree_rows(page)
            if str(row.get("text") or "").strip() == name]
    return rows[0] if len(rows) == 1 else (None, None)


def _click_rendered(root, row: dict) -> None:
    element_id = str(row.get("id") or "")
    if not element_id:
        raise RuntimeError("GSCM rendered the bookmark without a usable row element; retry after rendering settles.")
    # Element IDs are generated by Nexacro, but this exact freshly rendered
    # element is only used for a normal single click, never as identity.
    root.locator("[id=" + repr(element_id) + "]").first.click(timeout=15_000)


def _scroll_once(page) -> bool:
    """Use only the visible Favorite scrollbar increment and prove a repaint."""
    before = flow_gscm._tree_row_signature(page)
    for root in flow_gscm._roots(page):
        increment = root.locator("[id*='" + flow_gscm.FAVORITE_GRID_ID_SUFFIX + ".vscrollbar.incbutton']").first
        try:
            if not increment.count():
                continue
            increment.click(timeout=15_000)
            page.wait_for_timeout(250)
            if flow_gscm._tree_row_signature(page) != before:
                return True
        except Exception:
            continue
    return False


def select(page, step: dict, progress=None) -> dict:
    """Reveal and click a bookmark without changing the recorded journey."""
    target = step["bookmark_target"]
    identity = _identity(page, target)
    name = identity["identity_name"]
    started = time.monotonic()
    movement = False
    root, row = _rendered_target(page, name)
    while row is None:
        if time.monotonic() - started >= DEADLINE_SECONDS:
            raise RuntimeError(f"GSCM Favorite bookmark {name!r} was not rendered within the 120-second step deadline.")
        if not _scroll_once(page):
            raise RuntimeError(f"GSCM Favorite bookmark {name!r} is not rendered and its current grid scrollbar did not move. Its ancestor may be collapsed; restore the recorded folder state and retry.")
        movement = True
        root, row = _rendered_target(page, name)
    _click_rendered(root, row)
    result = {"strategy": "favorite-scrollbar" if movement else "favorite-visible-row",
              "movement": movement, "rendered": True, "bookmark_id": identity["bookmark_id"],
              "bookmark_name": name, "scope": identity.get("tab")}
    if progress:
        progress({"phase": "gscm_bookmark_selected", "bookmark": result})
    return result
