"""Recorded browser actions: data-only import, validation and date resolution.

This module has no database, web server or browser dependency. Codegen input
is parsed, never imported or evaluated. The same definitions travel with the
portable script and the worker's frozen job.
"""
from __future__ import annotations

import ast
import copy
import hashlib
import json
import re
from datetime import date, datetime, timedelta
from urllib.parse import urlsplit
from zoneinfo import ZoneInfo
from app.flow_clock import TIMEZONE

VERSION = 5
V2_CAPABILITY = 'recorded_flows_v2'
V3_CAPABILITY = 'recorded_flows_v3'
V4_CAPABILITY = 'recorded_flows_v4'
V5_CAPABILITY = 'recorded_flows_v5'
CAPABILITY = 'recorded_flows_v1'
GSCM_BOOKMARK_CAPABILITY = 'gscm_bookmark_targets_v1'
RECORD_CAPABILITY = 'flow_recorder_v1'
LOCATORS = {'locator', 'get_by_role', 'get_by_label', 'get_by_text', 'get_by_placeholder',
            'get_by_title', 'get_by_alt_text', 'get_by_test_id', 'frame_locator', 'filter', 'nth'}
ACTIONS = {'click', 'dblclick', 'fill', 'press', 'select_option', 'check', 'uncheck',
           'set_checked', 'hover', 'clear', 'press_sequentially'}
ASSERTIONS = {'to_be_visible', 'to_be_hidden', 'to_have_text', 'to_contain_text',
              'to_have_value', 'to_be_checked', 'to_have_url', 'to_have_title', 'to_have_count'}
CALCULATIONS = {'today', 'yesterday', 'month_start', 'previous_month_start',
                'previous_month_end', 'year_start', 'week_start'}
# Week parameters drive date range controls; the newest selectable week is
# read from the control itself at run time, the others are calendar maths.
WEEK_CALCULATIONS = {'latest_selectable', 'current_week', 'previous_week'}
WEEK_FORMATS = {'%G-W%V': re.compile(r'(20\d{2})-W(0[1-9]|[1-4]\d|5[0-3])'),
                '%G%V': re.compile(r'(20\d{2})(0[1-9]|[1-4]\d|5[0-3])')}
DAY_FORMATS = {'%Y-%m-%d', '%d/%m/%Y', '%m/%d/%Y', '%Y%m%d'}
MAX_WEEK_OFFSET = 520
MONTH_CALCULATIONS = {'oldest_selectable', 'latest_selectable', 'current_month', 'previous_month'}
MONTH_FORMATS = {'%Y%m': re.compile(r'(20\d{2})(0[1-9]|1[0-2])')}
MAX_MONTH_OFFSET = 120
SENSITIVE = re.compile(r'password|passwd|authorization|cookie|token|secret|otp|verification.?code', re.I)


def canonical(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(',', ':'))


def suggest_review(definition):
    """Preserve captured actions without adding page checks to the recording."""
    result = copy.deepcopy(definition)
    # These fields were generated by an older review screen, not recorded
    # actions. Explicit browser assertions remain in the steps themselves.
    for key in ('identity', 'identity_candidates', 'readiness'):
        result.pop(key, None)
    return result


def digest(value):
    return hashlib.sha256(canonical(value).encode()).hexdigest()


def parameter_unit(parameter):
    return parameter.get('unit', 'day')


def parameter_format(parameter):
    defaults = {'day': '%Y-%m-%d', 'week': '%G-W%V', 'month': '%Y%m'}
    return parameter.get('format', defaults.get(parameter_unit(parameter), '%Y-%m-%d'))


def parse_week(text, fmt='%G-W%V'):
    """The Monday of an ISO week written as YYYY-Www or YYYYWW."""
    pattern = WEEK_FORMATS.get(fmt)
    if pattern is None:
        raise ValueError('Unsupported week format.')
    match = pattern.fullmatch(str(text or '').strip())
    if not match:
        raise ValueError('Week values must use ' + ('YYYYWW' if fmt == '%G%V' else 'YYYY-Www') + '.')
    try:
        return date.fromisocalendar(int(match.group(1)), int(match.group(2)), 1)
    except ValueError:
        raise ValueError(f'The week {text} does not exist in that year.') from None


def week_monday(day, week_days='sunday'):
    """Monday of the ISO week that owns ``day`` under a control's week convention.

    ASAP weeks run Sunday to Saturday: a Sunday belongs to the ISO week that
    starts the next day. ISO weeks run Monday to Sunday.
    """
    anchor = day + timedelta(days=1) if week_days == 'sunday' else day
    return anchor - timedelta(days=anchor.weekday())


def week_bounds(monday, week_days='sunday'):
    """First and last calendar day of the week that ISO-starts on ``monday``."""
    first = monday - timedelta(days=1) if week_days == 'sunday' else monday
    return first, first + timedelta(days=6)


def format_week(day, fmt='%G-W%V'):
    iso = day.isocalendar()
    return f'{iso[0]:04d}{iso[1]:02d}' if fmt == '%G%V' else f'{iso[0]:04d}-W{iso[1]:02d}'


def parse_month(text, fmt='%Y%m'):
    """The first day of a month written as YYYYMM."""
    pattern = MONTH_FORMATS.get(fmt)
    if pattern is None:
        raise ValueError('Unsupported month format.')
    match = pattern.fullmatch(str(text or '').strip())
    if not match:
        raise ValueError('Month values must use YYYYMM.')
    return date(int(match.group(1)), int(match.group(2)), 1)


def format_month(day, fmt='%Y%m'):
    if fmt not in MONTH_FORMATS:
        raise ValueError('Unsupported month format.')
    return day.strftime('%Y%m')


def add_months(day, offset):
    ordinal = day.year * 12 + day.month - 1 + offset
    return date(ordinal // 12, ordinal % 12 + 1, 1)


def parse_parameter_value(parameter, value):
    """A date parameter's text as a datetime; weeks resolve to their Monday."""
    fmt = parameter_format(parameter)
    if parameter_unit(parameter) == 'week':
        monday = parse_week(value, fmt)
        return datetime(monday.year, monday.month, monday.day)
    if parameter_unit(parameter) == 'month':
        month = parse_month(value, fmt)
        return datetime(month.year, month.month, 1)
    return datetime.strptime(value, fmt)


def _literal(node):
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name) and node.func.value.id == 're' and node.func.attr == 'compile':
        if len(node.args) != 1 or node.keywords:
            raise ValueError('Use a plain regular expression without dynamic flags.')
        return {'regex': ast.literal_eval(node.args[0])}
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError):
        raise ValueError('Recorded arguments must be literal values.') from None


def _arguments(node):
    if any(item.arg is None for item in node.keywords):
        raise ValueError('Expanded keyword arguments are unsupported.')
    return [_literal(item) for item in node.args], {item.arg: _literal(item.value) for item in node.keywords}


def _target(node, pages):
    if isinstance(node, ast.Name) and node.id in pages:
        return {'page': pages[node.id], 'locator': []}
    if isinstance(node, ast.Attribute) and node.attr in {'first', 'last', 'content_frame'}:
        target = _target(node.value, pages)
        target['locator'].append({'method': node.attr, 'args': [], 'kwargs': {}})
        return target
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr in LOCATORS:
        target = _target(node.func.value, pages)
        args, kwargs = _arguments(node)
        target['locator'].append({'method': node.func.attr, 'args': args, 'kwargs': kwargs})
        return target
    raise ValueError('Unsupported page or locator expression.')


def walk_steps(steps, _depth=0):
    if not isinstance(steps, list) or _depth > 20:
        raise ValueError('Recording steps must be a list with at most 20 nested events.')
    for step in steps:
        if not isinstance(step, dict):
            raise ValueError('Every recorded step must be an action object.')
        yield step
        yield from walk_steps(step.get('steps', []), _depth + 1)


def _validate_target(target, *, activation):
    if not isinstance(target, dict) or not isinstance(target.get('locator', []), list):
        raise ValueError('Invalid recorded locator.')
    if target and (not isinstance(target.get('page'), str) or not target['page']):
        raise ValueError('Every locator must identify its page.')
    for part in target.get('locator', []):
        if (not isinstance(part, dict) or part.get('method') not in LOCATORS | {'first', 'last', 'content_frame'}
                or not isinstance(part.get('args', []), list) or not isinstance(part.get('kwargs', {}), dict)):
            raise ValueError('Unsupported locator or arguments.')


def _validate_pages(steps, pages=None, created=None, snapshots=None):
    pages = {'page'} if pages is None else pages
    created = set() if created is None else created
    snapshots = {} if snapshots is None else snapshots
    for step in steps:
        snapshots[step['id']] = set(pages)
        name = step.get('page')
        if not isinstance(name, str) or not name:
            raise ValueError('Every action must identify its page.')
        if step['action'] == 'wait':
            continue
        if step['action'] == 'new_page':
            if name in created or (name in pages and name != 'page'):
                raise ValueError('A page identity cannot be reused.')
            pages.add(name)
            created.add(name)
        elif name not in pages:
            raise ValueError('An action references an unopened or closed page.')
        if step['action'] in {'popup', 'download'}:
            _validate_pages(step['steps'], pages, created, snapshots)
        elif step.get('steps'):
            raise ValueError('Only popup and download events may contain nested actions.')
        if step['action'] == 'popup':
            result = step.get('result_page')
            if not isinstance(result, str) or not result or result in pages or result in created:
                raise ValueError('A popup requires a new page identity.')
            pages.add(result)
            created.add(result)
        if step['action'] == 'close':
            pages.remove(name)
            created.add(name)
    return snapshots


def import_codegen(source, *, timezone=TIMEZONE):
    if len(source.encode()) > 1_000_000:
        raise ValueError('Recording exceeds the one megabyte limit.')
    tree = ast.parse(source)
    functions = [node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == 'run']
    if len(functions) != 1:
        raise ValueError('Expected one Playwright Python run function.')
    if functions[0].decorator_list or functions[0].args.defaults or functions[0].args.kw_defaults:
        raise ValueError('Decorated or parameterized recording wrappers are unsupported.')
    # Only the standard codegen scaffolding may exist outside the run function.
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            names = [node.module] if isinstance(node, ast.ImportFrom) else [item.name for item in node.names]
            if not all(name in {'re', 'playwright.sync_api'} for name in names):
                raise ValueError('Recording contains an unsupported import.')
        elif node is functions[0]:
            continue
        elif isinstance(node, ast.With) and len(node.items) == 1 and ast.unparse(node.items[0].context_expr) == 'sync_playwright()':
            if len(node.body) != 1 or not isinstance(node.body[0], ast.Expr) or ast.unparse(node.body[0].value) != 'run(playwright)':
                raise ValueError('Unsupported code outside the recording.')
        else:
            raise ValueError('Unsupported code outside the recording.')
    pages, pending = {}, {}
    count = 0

    def parse(nodes):
        nonlocal count
        steps = []
        for node in nodes:
            count += 1
            identity = f'step-{count:03d}'
            if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
                name, value = node.targets[0].id, node.value
                text = ast.unparse(value)
                if name == 'browser' and isinstance(value, ast.Call) and ast.unparse(value.func) == 'playwright.chromium.launch':
                    _arguments(value)
                    continue
                if name == 'context' and isinstance(value, ast.Call) and ast.unparse(value.func) == 'browser.new_context':
                    _arguments(value)
                    continue
                if text == 'context.new_page()':
                    pages[name] = name
                    steps.append({'id': identity, 'action': 'new_page', 'page': name})
                    continue
                if isinstance(value, ast.Attribute) and value.attr == 'value' and isinstance(value.value, ast.Name) and value.value.id in pending:
                    event = pending[value.value.id]
                    if event['action'] == 'popup':
                        event['result_page'] = name
                        pages[name] = name
                    else:
                        pending[name] = event
                    continue
                raise ValueError(f'Unsupported assignment on line {node.lineno}.')
            if isinstance(node, ast.With) and len(node.items) == 1:
                item = node.items[0]
                call = item.context_expr
                if not isinstance(call, ast.Call) or not isinstance(call.func, ast.Attribute) or call.func.attr not in {'expect_download', 'expect_popup'} or not isinstance(item.optional_vars, ast.Name):
                    raise ValueError(f'Unsupported event on line {node.lineno}.')
                args, kwargs = _arguments(call)
                if args or set(kwargs) - {'timeout'}:
                    raise ValueError('Unsupported event options.')
                target = _target(call.func.value, pages)
                event = {'id': identity, 'action': call.func.attr.removeprefix('expect_'), **target,
                         'steps': parse(node.body)}
                if event['action'] == 'download':
                    event['output'] = {'format': 'xlsx'}
                steps.append(event)
                pending[item.optional_vars.id] = event
                continue
            if not isinstance(node, ast.Expr) or not isinstance(node.value, ast.Call):
                raise ValueError(f'Unsupported statement on line {node.lineno}.')
            call = node.value
            if not isinstance(call.func, ast.Attribute):
                raise ValueError('Only recorded browser interactions are supported.')
            method, receiver = call.func.attr, call.func.value
            if (method == 'once' and isinstance(receiver, ast.Name) and receiver.id in pages
                    and len(call.args) == 2 and not call.keywords
                    and isinstance(call.args[0], ast.Constant) and call.args[0].value == 'dialog'
                    and isinstance(call.args[1], ast.Lambda)
                    and ast.unparse(call.args[1]) == 'lambda dialog: dialog.dismiss()'):
                # Playwright codegen adds this when an action opens a native
                # dialog. Playback already uses Playwright's automatic dialog
                # handling. Drop only this exact generated callback; never
                # evaluate source callbacks or accept arbitrary event handlers.
                continue
            if method == 'close' and isinstance(receiver, ast.Name) and receiver.id in {'browser', 'context'}:
                if call.args or call.keywords:
                    raise ValueError('Unsupported close arguments.')
                continue
            if method == 'storage_state' and isinstance(receiver, ast.Name) and receiver.id == 'context':
                # codegen --save-storage adds this cleanup statement. The
                # worker owns protected authentication; never export its path
                # or execute this source statement as part of a Flow.
                args, kwargs = _arguments(call)
                if args or set(kwargs) != {'path'} or not isinstance(kwargs['path'], str):
                    raise ValueError('Unsupported recording storage-state cleanup.')
                continue
            if method == 'save_as' and isinstance(receiver, ast.Name) and receiver.id in pending:
                # The worker chooses staging/output paths. Ignore only the
                # literal output path; never execute a recorded filesystem call.
                args, kwargs = _arguments(call)
                if len(args) != 1 or kwargs or not isinstance(args[0], str):
                    raise ValueError('Unsupported download save path.')
                continue
            if method in ASSERTIONS and isinstance(receiver, ast.Call) and isinstance(receiver.func, ast.Name) and receiver.func.id == 'expect' and len(receiver.args) == 1:
                target = _target(receiver.args[0], pages)
                args, kwargs = _arguments(call)
                steps.append({'id': identity, 'action': 'assert', 'assertion': method, **target, 'args': args, 'kwargs': kwargs})
                continue
            if method not in ACTIONS | {'goto', 'close'}:
                raise ValueError(f'Unsupported action {method!r} on line {node.lineno}.')
            target = _target(receiver, pages)
            args, kwargs = _arguments(call)
            if kwargs.get('position') or kwargs.get('force'):
                raise ValueError('Coordinate and forced clicks must be re-recorded with a semantic locator.')
            steps.append({'id': identity, 'action': method, **target, 'args': args, 'kwargs': kwargs})
        return steps

    steps = parse(functions[0].body)
    # Plain codegen still uses the v4 contract. Version 5 is promoted only
    # when the editor adds automatic slider discovery or month parameters.
    definition = {'version': 4, 'timezone': timezone, 'steps': steps, 'parameters': {}}
    validate_definition(definition, activation=False)
    return suggest_review(definition)


def validate_definition(definition, *, activation=True):
    if not isinstance(definition, dict) or definition.get('version') not in set(range(1, VERSION + 1)):
        raise ValueError('Unsupported recording version.')
    if 'date_batch' in definition:
        raise ValueError('Date batching has been removed. Convert this recording to a single range and test it.')
    if len(canonical(definition).encode()) > 1_000_000:
        raise ValueError('Recording exceeds the one megabyte limit.')
    ZoneInfo(definition.get('timezone', 'UTC'))
    parameters = definition.get('parameters', {})
    if not isinstance(parameters, dict) or any(not isinstance(p, dict) for p in parameters.values()):
        raise ValueError('Recording parameters must be named date definitions.')
    if definition.get('browser_channel', 'msedge') not in {'msedge', 'chrome', 'chromium'}:
        raise ValueError('Choose Edge, Chrome or Chromium.')
    steps = list(walk_steps(definition.get('steps', [])))
    if not steps or len(steps) > 500:
        raise ValueError('A recording needs between 1 and 500 steps.')
    ids = [step.get('id') for step in steps]
    if not all(isinstance(item, str) and item for item in ids) or len(set(ids)) != len(ids):
        raise ValueError('Recording step identifiers must be unique.')
    downloads = []
    for step in steps:
        if not isinstance(step, dict) or not isinstance(step.get('args', []), list) or not isinstance(step.get('kwargs', {}), dict):
            raise ValueError('Invalid action arguments.')
        action = step.get('action')
        _validate_target(step, activation=activation)
        if step.get('bookmark_target') is not None:
            from app.flow_recording_gscm_bookmark import validate_target
            validate_target(step)
        if activation and step.get('repair_reason'):
            raise ValueError(f"{step['id']}: {step['repair_reason']}")
        if definition.get('adapter') == 'gscm_portal' and activation and step.get('bookmark_target') is None:
            # A bookmark-target click keeps its recorded locator only as page/
            # frame context; playback resolves the bookmark by exact identity.
            from app.flow_recording_nexacro import validate_target
            validate_target(step)
        if action not in ACTIONS | {'new_page', 'goto', 'close', 'download', 'popup', 'assert', 'wait', 'select_range', 'set_range'}:
            raise ValueError(f'Unsupported recorded action: {action}.')
        if 'delay_before_seconds' in step:
            delay = step['delay_before_seconds']
            if action not in ACTIONS or type(delay) is not int or not 1 <= delay <= 600:
                raise ValueError('Wait before this step needs a browser interaction and whole seconds from 1 to 600.')
        if 'label' in step and (not isinstance(step['label'], str) or len(step['label']) > 160):
            raise ValueError('Step names must be text of at most 160 characters.')
        if action == 'wait':
            if definition['version'] < 2 or type(step.get('seconds')) is not int or not 1 <= step['seconds'] <= 600:
                raise ValueError('Wait steps need version 2 and a whole number of seconds from 1 to 600.')
            if step.get('locator') or step.get('args') or step.get('kwargs'):
                raise ValueError('Wait steps cannot target an element or contain browser arguments.')
        if action == 'select_range':
            if definition['version'] < 3:
                raise ValueError('Range steps require recording version 3.')
            contract = step.get('range')
            if not isinstance(contract, dict) or contract.get('unit') != 'week':
                raise ValueError('A range step must select weeks.')
            if not re.fullmatch(r'20\d{2}-W(?:0[1-9]|[1-4]\d|5[0-3])', str(contract.get('start') or '')):
                raise ValueError('A week range needs an ISO start such as 2026-W01.')
            if contract.get('end') != 'latest_selectable' or contract.get('selection') != 'inclusive':
                raise ValueError('A week range must include its start through the latest selectable week.')
            selector = contract.get('cell_selector')
            if not isinstance(selector, str) or not selector.strip() or len(selector) > 500:
                raise ValueError('A week range needs a bounded cell selector.')
            state = contract.get('selected_state', 'auto')
            if state not in {'auto', 'checked', 'aria-checked', 'aria-selected', 'aria-pressed'} and not re.fullmatch(r'class:[A-Za-z_-][\w-]{0,79}', str(state)):
                raise ValueError('A week range needs a supported selected-state signal.')
            navigation = contract.get('navigation', {'kind': 'scroll'})
            if not isinstance(navigation, dict) or navigation.get('kind', 'scroll') not in {'scroll', 'none', 'controls'}:
                raise ValueError('A week range needs scroll, controls, or no-navigation behavior.')
            if navigation.get('kind') == 'controls':
                for name in ('next_selector', 'previous_selector'):
                    value = navigation.get(name)
                    if not isinstance(value, str) or not value.strip() or len(value) > 500:
                        raise ValueError('Range navigation controls need bounded next and previous selectors.')
            select_all = contract.get('select_all_selector')
            if select_all is not None and (not isinstance(select_all, str) or not select_all.strip() or len(select_all) > 500):
                raise ValueError('A range Select all target needs a bounded selector.')
            if not step.get('locator'):
                raise ValueError('A week range must identify its containing element box.')
        if action == 'set_range':
            if definition['version'] < 4:
                raise ValueError('Date range control steps require recording version 4.')
            contract = step.get('range')
            if not isinstance(contract, dict) or contract.get('kind') not in {'week', 'date', 'month'}:
                raise ValueError('A date range control shows weeks, dates or months.')
            if contract.get('kind') == 'month' and definition['version'] < 5:
                raise ValueError('Month range controls require recording version 5.')
            if contract.get('kind') != 'month' and contract.get('week_days', 'sunday') not in {'sunday', 'monday'}:
                raise ValueError('A date range control week starts on Sunday or Monday.')
            levels = contract.get('container_ancestor_levels', 1)
            minimum = 0 if definition['version'] >= 5 else 1
            if type(levels) is not int or not minimum <= levels <= 6:
                raise ValueError('Choose automatic detection or 1–6 parent levels for the element box.')
            if not step.get('locator'):
                raise ValueError('A date range control must identify its containing element box.')
            roles = sorted(str(p.get('role')) for p in parameters.values() if p.get('step_id') == step['id'])
            if roles != ['end', 'start']:
                raise ValueError('A date range control needs exactly one start and one end parameter.')
        if action == 'assert' and step.get('assertion') not in ASSERTIONS:
            raise ValueError('Unsupported assertion.')
        if step.get('kwargs', {}).get('force') or step.get('kwargs', {}).get('position') or step.get('kwargs', {}).get('trial'):
            raise ValueError('Forced or coordinate actions are unsupported.')
        timeout = step.get('kwargs', {}).get('timeout', 120_000)
        if not isinstance(timeout, (int, float)) or not 0 < timeout <= 1_800_000:
            raise ValueError('Action timeouts must be bounded between 1 and 1800000 milliseconds.')
        if action == 'goto':
            args = step.get('args', [])
            if len(args) != 1 or not isinstance(args[0], str):
                raise ValueError('Navigation requires one URL.')
            url = urlsplit(args[0])
            if url.scheme not in {'http', 'https'} or not url.hostname or url.username or url.password:
                raise ValueError('Recording navigation requires an HTTP(S) URL without credentials.')
            if re.search(r'(?:[?&])[^=&]*(?:token|password|secret|ticket|code)=', args[0], re.I):
                raise ValueError('Record from a stable portal URL without authentication parameters.')
        if action in {'fill', 'press_sequentially'} and SENSITIVE.search(canonical(step.get('locator', []))):
            raise ValueError('Authentication inputs cannot be included in a recording. Sign in first.')
        if action == 'popup' and not step.get('result_page'):
            raise ValueError('Popup has no recorded page identity.')
        if action in {'download', 'popup'} and not step.get('steps'):
            raise ValueError('An event must contain its triggering action.')
        if action == 'download':
            downloads.append(step)
            output = step.get('output', {})
            if not isinstance(output, dict) or output.get('format') not in {'csv', 'xlsx', 'html', 'txt'}:
                raise ValueError('Choose CSV, Excel, HTML or text for every download.')
            if (not isinstance(output.get('headers', []), list) or
                    any(not isinstance(h, str) or not h for h in output.get('headers', [])) or
                    output.get('completion', 'native') not in {'native', 'staging'}):
                raise ValueError('Invalid expected output schema or completion method.')
            if type(output.get('min_rows', 0)) is not int or output.get('min_rows', 0) < 0:
                raise ValueError('Minimum data rows must be a whole number of zero or more.')
            checks = output.get('period_checks', [])
            if not isinstance(checks, list) or any(not isinstance(c, dict) or not isinstance(c.get('column'), str)
                    or not c['column'] or c.get('parameter') not in parameters for c in checks):
                raise ValueError('Period checks require a column and a known date parameter.')
            if output['format'] in {'html', 'txt'} and (output.get('min_rows') or output.get('headers') or checks):
                raise ValueError('Data checks require CSV or Excel output.')
    _validate_pages(definition['steps'])
    if activation and not downloads:
        raise ValueError('The recording did not capture a download. Record through the download button.')
    # Legacy review metadata never adds execution requirements. Only captured
    # assertion steps and explicitly configured output checks are replayed.
    for target in [p.get('target', {}) for p in parameters.values()]:
        _validate_target(target, activation=activation)
        if definition.get('adapter') == 'gscm_portal' and activation:
            from app.flow_recording_nexacro import validate_target
            validate_target(target)
    for name, parameter in definition.get('parameters', {}).items():
        if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]{0,63}', name):
            raise ValueError('Use a simple parameter name.')
        if parameter.get('mode') not in {'portal_default', 'fixed', 'calculated'}:
            raise ValueError('Unsupported date parameter mode.')
        if (parameter.get('step_id') and parameter['step_id'] not in ids) or (not parameter.get('step_id') and not parameter.get('target')):
            raise ValueError('A parameter must identify a recorded step or input locator.')
        if parameter.get('not_after') and parameter['not_after'] not in definition.get('parameters', {}):
            raise ValueError('Date range references an unknown parameter.')
        unit = parameter_unit(parameter)
        if unit not in {'day', 'week', 'month'}:
            raise ValueError('Unsupported date parameter unit.')
        action = next((step['action'] for step in steps if step['id'] == parameter.get('step_id')), None)
        range_kind = next((step.get('range', {}).get('kind') for step in steps
                           if step['id'] == parameter.get('step_id')), None)
        fmt = parameter_format(parameter)
        if unit == 'week':
            if definition['version'] < 4:
                raise ValueError('Week parameters require recording version 4.')
            if action != 'set_range' or parameter.get('role') not in {'start', 'end'}:
                raise ValueError('Week parameters belong to a date range control as its start or end.')
            if range_kind == 'month':
                raise ValueError('A month range control needs month parameters.')
            if fmt not in WEEK_FORMATS:
                raise ValueError('Unsupported week format.')
            if parameter.get('mode') == 'calculated' and parameter.get('expression') not in WEEK_CALCULATIONS:
                raise ValueError('Unsupported week calculation.')
            offset = parameter.get('offset_weeks', 0)
            if type(offset) is not int or abs(offset) > MAX_WEEK_OFFSET:
                raise ValueError('Week offsets must be whole weeks within ten years.')
            if parameter.get('mode') == 'fixed':
                parse_week(parameter.get('value', ''), fmt)
            continue
        if unit == 'month':
            if definition['version'] < 5:
                raise ValueError('Month parameters require recording version 5.')
            if action != 'set_range' or range_kind != 'month' or parameter.get('role') not in {'start', 'end'}:
                raise ValueError('Month parameters belong to a month range control as its start or end.')
            if fmt not in MONTH_FORMATS:
                raise ValueError('Unsupported month format.')
            if parameter.get('mode') == 'calculated' and parameter.get('expression') not in MONTH_CALCULATIONS:
                raise ValueError('Unsupported month calculation.')
            offset = parameter.get('offset_months', 0)
            if type(offset) is not int or abs(offset) > MAX_MONTH_OFFSET:
                raise ValueError('Month offsets must be whole months within ten years.')
            if parameter.get('mode') == 'fixed':
                parse_month(parameter.get('value', ''), fmt)
            continue
        if action == 'set_range':
            raise ValueError('A date range control needs matching week or month parameters.')
        if parameter.get('step_id'):
            if action not in {'fill', 'select_option', 'press_sequentially'}:
                raise ValueError('Date parameters must reference value-setting steps.')
        elif parameter.get('mode') != 'portal_default':
            raise ValueError('Fixed/calculated dates require a recorded value-setting step.')
        if parameter.get('mode') == 'calculated' and parameter.get('expression') not in CALCULATIONS:
            raise ValueError('Unsupported date calculation.')
        if fmt not in DAY_FORMATS:
            raise ValueError('Unsupported date format.')
        if parameter.get('mode') == 'fixed':
            datetime.strptime(parameter.get('value', ''), fmt)
    return definition


def resolve_parameters(definition, overrides=None, *, now=None):
    zone = ZoneInfo(definition['timezone'])
    now = now or datetime.now(zone)
    now = now.replace(tzinfo=zone) if now.tzinfo is None else now.astimezone(zone)
    day = now.astimezone(ZoneInfo(definition['timezone'])).date()
    month_start = day.replace(day=1)
    previous_end = month_start - timedelta(days=1)
    values = {'today': day, 'yesterday': day - timedelta(days=1), 'month_start': month_start,
              'previous_month_start': previous_end.replace(day=1), 'previous_month_end': previous_end,
              'year_start': day.replace(month=1, day=1), 'week_start': day - timedelta(days=day.weekday())}
    overrides = overrides or {}
    unknown = set(overrides) - set(definition.get('parameters', {}))
    if unknown:
        raise ValueError('Unknown parameter: ' + sorted(unknown)[0])
    steps = {step['id']: step for step in walk_steps(definition.get('steps', []))}
    result = {}
    for name, parameter in definition.get('parameters', {}).items():
        mode, fmt = parameter['mode'], parameter_format(parameter)
        value = overrides.get(name)
        if value is None and mode == 'fixed':
            value = parameter.get('value')
        elif value is None and mode == 'calculated':
            unit = parameter_unit(parameter)
            if unit == 'week':
                # Calendar weeks follow the control's own week convention, so a
                # Sunday already belongs to the new week on an ASAP control. The
                # newest selectable week exists only on the live control.
                contract = steps.get(parameter.get('step_id'), {}).get('range') or {}
                monday = week_monday(day, contract.get('week_days', 'sunday'))
                anchors = {'current_week': monday, 'previous_week': monday - timedelta(days=7)}
                anchor = anchors.get(parameter['expression'])
                if anchor is not None:
                    value = format_week(anchor + timedelta(weeks=parameter.get('offset_weeks', 0)), fmt)
            elif unit == 'month':
                anchors = {'current_month': month_start, 'previous_month': previous_end.replace(day=1)}
                anchor = anchors.get(parameter['expression'])
                if anchor is not None:
                    value = format_month(add_months(anchor, parameter.get('offset_months', 0)), fmt)
            else:
                value = values[parameter['expression']].strftime(fmt)
        if value is not None:
            parse_parameter_value(parameter, value)
        result[name] = value
    return result
