table Employee_Roster
	lineageTag: 064c333f-170f-434e-b08d-ce575ccfdfb3

	column employee_id
		dataType: string
		lineageTag: 9e4b90b4-7e2e-4dd7-a6c9-875cca3a45d5
		summarizeBy: none
		sourceColumn: employee_id

	column name
		dataType: string
		lineageTag: 604b07f0-c2ff-4b94-b91f-c87917d57c0a
		summarizeBy: none
		sourceColumn: name

	column department
		dataType: string
		lineageTag: 16f3d49f-ddaa-4384-bf76-929fae06e2a7
		summarizeBy: none
		sourceColumn: department

	column hire_date
		dataType: string
		lineageTag: 1b36eb87-32bb-41e6-8344-00ab7e2958da
		summarizeBy: none
		sourceColumn: hire_date

	partition Employee_Roster = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\HR\employee_roster.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
