table Targets

	column KPIName
		dataType: string
		sourceColumn: KPIName

	column TargetValue
		dataType: decimal
		sourceColumn: TargetValue

	column Period
		dataType: string
		sourceColumn: Period

	column Owner
		dataType: string
		sourceColumn: Owner

	partition 'targets-partition' = m
		mode: import
		source =
			let
			    Source = Excel.Workbook(File.Contents("\\fileserver\shared\Finance\kpi_targets.xlsx"), null, true),
			    #"2024_Sheet" = Source{[Item="2024",Kind="Sheet"]}[Data],
			    #"Promoted Headers" = Table.PromoteHeaders(#"2024_Sheet", [PromoteAllScalars=true])
			in
			    #"Promoted Headers"
