table Categories
	lineageTag: b8c9d0e1-8888-9999-0000-111122223333

	column category_id
		dataType: string
		lineageTag: 66667777-aaaa-bbbb-cccc-ddddeeee1111
		summarizeBy: none
		sourceColumn: category_id

	column category_name
		dataType: string
		lineageTag: 77778888-aaaa-bbbb-cccc-ddddeeee2222
		summarizeBy: none
		sourceColumn: category_name

	partition Categories = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Categories.csv"),[Delimiter=";", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
