from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch()
 page=b.new_page(viewport={'width':1280,'height':900})
 page.set_default_timeout(12000)
 page.goto('http://127.0.0.1:8769/static/recording-preview/index.html')
 page.locator('#reset').click()
 page.locator('#record').click()
 page.locator('#start').click()
 page.locator('#finish').click()
 assert page.locator('.steps>li').count()==8
 assert page.locator('#fresh').count()==0
 assert page.locator('#step').count()==0
 for w,h,name in [(1280,900,'minimal-desktop'),(390,844,'minimal-narrow')]:
  page.set_viewport_size({'width':w,'height':h})
  assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
  page.screenshot(path=f'app/static/recording-preview/{name}.png',full_page=True)
 page.locator('[data-step="5"]').click()
 page.locator('#step').fill('Run Regional Orders')
 page.locator('#editstep').click()
 page.locator('#undo').click()
 page.locator('#done').click()
 page.locator('#test').click()
 page.get_by_text('Test passed · 2 files ready. Return to Edit Flow to save.',exact=True).wait_for()
 page.locator('.review-actions').get_by_role('button',name='Back to Edit Flow').click()
 page.locator('#apply').click()
 page.locator('#reopen').click()
 page.locator('#outcome').select_option('missing')
 page.locator('#record').click()
 page.get_by_text('More',exact=True).click()
 page.locator('#replace').click()
 page.locator('#confirmreplace').click()
 page.locator('#finish').click()
 page.locator('#test').click()
 assert page.locator('#check-value').evaluate('(el)=>el===document.activeElement')
 page.locator('#later').click()
 page.locator('#test').click()
 page.locator('#check-value').fill('Results updated')
 page.get_by_role('button',name='Continue test').click()
 page.get_by_text('Test passed · 2 files ready. Return to Edit Flow to save.',exact=True).wait_for()
 print('PASS: minimal review, inline editing/undo, saved flow, contextual missing check, defer/retry, desktop and narrow layouts')
 b.close()
