import fs from 'node:fs';
import path from 'node:path';
const base=path.resolve(import.meta.dirname,'..'); process.chdir(base);
const narration=JSON.parse(fs.readFileSync('narration.json','utf8'));
const mark=`<svg viewBox="0 0 32 32" fill="none" aria-label="Metronome"><path d="M10 27h12L19 5h-6l-3 22Z" fill="#e2f1ef" stroke="#0d7377" stroke-width="2"/><path d="m16 8 5 13M8 27h16" stroke="#0d7377" stroke-width="2.2" stroke-linecap="round"/><rect x="17" y="13" width="5" height="4" rx="1" fill="#0d7377"/></svg>`;
const logo=`<span class="logo">${mark}<b>Metronome</b></span>`;
const icon=(name)=>{const paths={back:'M19 12H5m7-7-7 7 7 7',forward:'M5 12h14m-7-7 7 7-7 7',reload:'M20 11a8 8 0 1 0-2 6M20 4v7h-7',tune:'M4 7h3m4 0h9M4 17h9m4 0h3M7 4v6m10 4v6',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z',puzzle:'M4 5h6V3a2 2 0 0 1 4 0v2h6v6h-2a2 2 0 0 0 0 4h2v6h-6v-2a2 2 0 0 0-4 0v2H4v-6h2a2 2 0 0 0 0-4H4Z',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',db:'M4 6c0-5 16-5 16 0s-16 5-16 0Zm0 0v12c0 5 16 5 16 0V6M4 12c0 5 16 5 16 0',check:'m5 12 4 4L19 6',moon:'M19 15A8 8 0 0 1 9 5a8 8 0 1 0 10 10',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z',arrow:'M4 12h16m-6-6 6 6-6 6'};return `<svg class="i" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${name==='more'?'<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>':`<path d="${paths[name]||paths.db}"/>`}</svg>`};
function chrome(title,url,body){return `<div class="chrome"><div class="chrome-tabs"><span class="tab-search">⌄</span><div class="chrome-tab">${title.startsWith("Metronome")?mark:`<span class="favicon">${title[0]}</span>`}<span>${title}</span>${icon('close')}</div><span class="new-tab">${icon('plus')}</span><div class="win-controls"><span>−</span><span>□</span><span>×</span></div></div><div class="chrome-toolbar">${icon('back')}<span class="disabled">${icon('forward')}</span>${icon('reload')}<div class="omnibox">${icon('tune')}<span>${url}</span>${icon('star')}</div>${icon('puzzle')}<span class="chrome-profile">M</span>${icon('more')}</div><div class="browser-content">${body}</div></div>`}
const rows=[['2026-09-28','UAE','MX-A101','12,480','6,420','GSCM + ASAP','Passed'],['2026-09-28','KSA','MX-A101','18,260','9,350','GSCM + ASAP','Passed'],['2026-09-28','Kuwait','MX-A101','4,680','2,710','GSCM + ASAP','Passed'],['2026-09-28','Qatar','MX-A101','3,240','1,880','GSCM + ASAP','Passed'],['2026-09-28','Bahrain','MX-A101','2,140','1,210','GSCM + ASAP','Passed'],['2026-09-28','Oman','MX-A101','2,850','1,640','GSCM + ASAP','Passed'],['2026-09-28','UAE','MX-A202','8,920','4,180','GSCM + ASAP','Passed'],['2026-09-28','KSA','MX-A202','11,650','6,290','GSCM + ASAP','Passed']];
const excel=`<div class="excel"><div class="excel-ribbon"><div class="excel-title-cover">Metronome — Organized datasets.xlsx</div></div><div class="formula"><span>A1</span><b>×　✓　<i>ƒx</i></b><div>report_date</div></div><div class="excel-grid"><div class="column-letters"><i></i>${'ABCDEFG'.split('').map(l=>`<b>${l}</b>`).join('')}</div><div class="sheet-row header"><i>1</i>${['report_date','country','product_id','sell_out_units','stock_units','source','quality_status'].map(x=>`<b>${x}<small>⌄</small></b>`).join('')}</div>${rows.map((r,i)=>`<div class="sheet-row data-row" data-row="${i}"><i>${i+2}</i>${r.map(x=>`<span>${x}</span>`).join('')}</div>`).join('')}<div class="sheet-row blank"><i>10</i>${Array(7).fill('<span></span>').join('')}</div></div><div class="sheet-tabs"><span>‹　›　⋯</span><b class="active-sheet">Sell-out & stock</b><b>Shipments</b><b>Price history</b><b>Data dictionary</b><span>⊕</span></div><div class="excel-status"><span>Ready</span><span>8 rows · 7 columns</span><span>▦　▥　− ━━━━━ ● ━━━ +　100%</span></div></div>`;

const duration=144;
const cursor=`<svg class="pointer" viewBox="0 0 40 48"><path d="M4 3 33 28 21 30 27 43 20 46 14 32 4 41Z" fill="#fff" stroke="#172d38" stroke-width="2.5"/></svg>`;
const glyph=(name)=>{const paths={website:'M3 4h26v22H3Zm0 6h26M8 7h1m3 0h1',table:'M3 4h26v24H3Zm0 8h26M12 12v16M3 20h26',clock:'M16 3a13 13 0 1 0 0 26 13 13 0 0 0 0-26Zm0 6v8l6 4',server:'M4 3h24v11H4Zm0 15h24v11H4ZM9 8h1m-1 15h1m8-15h5m-5 15h5',mail:'M3 6h26v21H3Zm0 0 13 11L29 6',spark:'m16 2 4 10 10 4-10 4-4 10-4-10L2 16l10-4Z',code:'m11 8-8 8 8 8m10-16 8 8-8 8M18 3l-4 26',flow:'M4 12h8v8H4Zm16 0h8v8h-8ZM12 16h8M16 16V4h8'};return `<svg class="glyph" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round" stroke-linecap="round"><path d="${paths[name]||paths.table}"/></svg>`};
const aiNames=['ChatGPT','Claude','Gemini'];
const aiFiles=['openai.svg','claude-color.svg','gemini-color.svg'];
let logoSerial=0;
function aiLogo(i){let svg=fs.readFileSync('assets/brands/'+aiFiles[i],'utf8').replace(/<\?xml[^>]*>/g,'');const suffix='-'+(++logoSerial);const ids=[...svg.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);for(const id of ids){svg=svg.replaceAll('id="'+id+'"','id="'+id+suffix+'"').replaceAll('#'+id,'#'+id+suffix)}return svg.replace(/<svg/,'<svg class="ai-logo"')}
function app(title,body,active='Flows'){return `<div class="app"><nav class="appnav">${logo}<div>${['Flows','Database','AI Auditor'].map(n=>`<span class="${n===active?'active':''}">${n}</span>`).join('')}</div><span class="avatar">M</span></nav><div class="app-body"><h2>${title}</h2>${body}</div></div>`}
const markets=['중동 전체','아랍에미리트','사우디아라비아','쿠웨이트','카타르','오만','바레인'];
const values=[['49,650','46,300','52,150','▲ 5.0%','▲ 12.6%'],['12,480','11,260','14,030','▲ 12.4%','▲ 24.6%'],['18,260','18,510','17,960','▼ 1.6%','▼ 3.0%'],['4,680','4,510','4,970','▲ 6.2%','▲ 10.2%'],['3,240','2,980','3,460','▲ 6.8%','▲ 16.1%'],['2,850','2,630','2,910','▲ 2.1%','▲ 10.6%'],['2,140','1,980','2,270','▲ 6.1%','▲ 14.6%']];
function reportTable(gscm){return `<table class="report-table"><thead><tr><th rowspan="2">${gscm?'판매 법인':'지역 / 국가'}</th><th colspan="3">${gscm?'재고 수량':'판매 실적'}</th><th colspan="2">증감률</th></tr><tr><th>2025년 9월</th><th>2026년 8월</th><th>2026년 9월</th><th>전년비 (YoY)</th><th>전월비</th></tr></thead><tbody>${markets.map((m,i)=>`<tr class="report-row ${i===0?'total':''}"><th>${m}</th>${values[i].map((v,j)=>`<td class="${j>2?(v.includes('▲')?'up':'down'):''}">${gscm&&j<3?(Math.round(Number(v.replaceAll(',',''))*.68)).toLocaleString('en-US'):v}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function portal(gscm=false){return `<div class="report-portal ${gscm?'gscm':'asap'}"><div class="portal-top"><b>${gscm?'GSCM':'ASAP'}</b><nav>${gscm?'공급 계획　　재고 현황　　출하 관리':'경영정보　　판매분석　　정기보고서　　다운로드'}</nav><span>홍길동 ▾</span></div><div class="portal-layout">${gscm?'<aside><b>공급망 관리</b><span>재고 현황</span><span>입출고 조회</span><span>월별 실적</span><span>내보내기</span></aside>':''}<div class="portal-main"><h2>${gscm?'법인별 재고 현황':'국가별 판매 실적 조회'}</h2><div class="portal-filter"><span>조회기간 <b>2026년 9월 ▾</b></span><span>지역 <b>중동 ▾</b></span><button>조회</button></div><div class="table-actions"><span>${gscm?'재고 현황':'판매 실적'}</span><button>↓ 다운로드</button></div>${reportTable(gscm)}</div></div></div>`}
const sources=['ASAP','GSCM','Bigdata portal','Datahub','NERP','Email reports'];
const datasetNames=['Sales','Stock','Shipments','Price history'];
const map=`<div class="flow-map"><svg class="map-links" viewBox="0 0 1720 680"><g fill="none" stroke="#c9d5d6" stroke-width="2.5">${sources.map((_,i)=>`<path d="M370 ${75+i*106}C560 ${75+i*106} 540 340 700 340"/>`).join('')}<path d="M1020 340H1250"/></g><g class="flow-dashes" fill="none" stroke="#0d7377" stroke-width="5" stroke-linecap="round" stroke-dasharray="8 74">${sources.map((_,i)=>`<path d="M370 ${75+i*106}C560 ${75+i*106} 540 340 700 340"/>`).join('')}<path d="M1020 340H1250"/></g><path d="m1236 330 15 10-15 10" fill="none" stroke="#0d7377" stroke-width="3"/></svg><div class="source-column">${sources.map((s,i)=>`<div class="source-item" data-source="${i}"><span class="source-icon">${i===5?glyph('mail'):glyph(i===3?'server':'website')}</span><b>${s}</b></div>`).join('')}</div><div class="hub">${mark}<h2>Metronome</h2></div><div class="database"><h2>${icon('db')}Organized datasets</h2>${datasetNames.map((s,i)=>`<div class="dataset" data-dataset="${i}">${glyph('table')}<b>${s}</b>${icon('check')}</div>`).join('')}</div></div>`;
const useData=`<div class="use-excel frame">${excel}</div><div class="ai-tool-row">${aiNames.map((s,i)=>`<div>${aiLogo(i)}<b>${s}</b></div>`).join('')}</div><svg class="usage-connectors" viewBox="0 0 1920 1080"><path d="M960 735v68M560 850v-47h800v47M960 803v47" fill="none" stroke="#a7c9c4" stroke-width="3"/></svg>`;
const createFields=[['Website','asap.example','website'],['Data','Monthly sales report','table'],['Destination','Database → Sales','server'],['Schedule','Every day · 06:00','clock']];
const builder=app('Create a Flow',`<div class="builder-workspace"><div class="build-inputs">${createFields.map((s,i)=>`<div class="build-field" data-field="${i}"><div>${glyph(s[2])}<label>${s[0]}</label></div><strong data-value="${i}">${s[1]}</strong>${icon('check')}</div>`).join('')}</div><div class="pipeline-canvas"><div class="pipeline-nodes">${[['Collect','website'],['Transform','table'],['Load','server'],['Repeat','clock']].map((s,i)=>`<div class="pipeline-node" data-node="${i}">${glyph(s[1])}<b>${s[0]}</b></div>`).join('<span class="node-link">→</span>')}</div><div class="pipeline-status">${icon('check')}Pipeline created</div></div></div><button class="create-flow">Create Flow</button><div class="flow-cursor">${cursor}<i></i></div>`);
const noCode=`<div class="no-code-intro"><div class="code-sheet">${glyph('code')}<pre><span>import</span> requests\n\n<span>def</span> refresh_report():\n    data = collect()\n    rows = transform(data)\n    save(rows)\n\nschedule.every().day()</pre></div><div class="code-to-flow">→</div><div class="no-code-card">${mark}<h2>No code.</h2><div>${glyph('website')}→${glyph('table')}→${glyph('server')}</div></div></div>`;
const auditor=app('Local AI agents',`<div class="night-work"><div class="night-feature"><div class="night-icon">${icon('moon')}</div><strong>02:00 AM</strong><div class="local-chip">${glyph('server')}Local AI</div></div><div class="audit-scene"><div class="audit-db">${icon('db')}</div><div class="scan-beam"></div><div class="audit-checks">${['Missing data','Refresh issues','Blank rows'].map((s,i)=>`<div data-audit="${i}"><span>${icon('check')}</span><b>${s}</b></div>`).join('')}</div></div></div>`,'AI Auditor');
const issues=[['Missing reporting period','Sales'],['Refresh overdue','Stock'],['Blank rows detected','Shipments'],['Duplicate records','Price history'],['Unexpected row-count drop','Sales']];
const findings=app('5 issues flagged',`<div class="findings-layout"><div class="issue-list">${issues.map((s,i)=>`<div class="issue-row" data-issue="${i}"><span class="issue-symbol">!</span><b>${s[0]}</b><span>${s[1]}</span><em>›</em></div>`).join('')}</div><div class="issue-detail"><div class="detail-title"><span>!</span><h3>Refresh overdue</h3></div><div class="freshness-line"><div><b>Expected</b><strong>06:00</strong></div><span>→</span><div class="overdue"><b>Last updated</b><strong>Yesterday</strong></div></div><section><h4>Issue</h4><p>The stock dataset missed its scheduled refresh.</p></section><section class="proposed-fix"><h4>Proposed fix</h4><p>Check the source connection, rerun the Stock Flow, then verify the latest reporting date.</p><button>Review Flow →</button></section></div><div class="issue-cursor">${cursor}<i></i></div></div>`,'AI Auditor');
const metoLogo='<b class="meto-logo"><span>M</span>METO AI Portal</b>';
const dashboard=`<div class="meto-dashboard"><nav>${metoLogo}<div>Dashboards　　Library</div><span>● Data current</span></nav><div class="meto-body"><h2>Gulf operations</h2><div class="meto-kpis"><div><span>Stock cover</span><strong>4.2 <small>weeks</small></strong></div><div><span>Sell-out</span><strong>+12<small>%</small></strong></div><div><span>Delayed shipments</span><strong>2</strong></div></div><div class="meto-chart"><h3>Stock cover</h3><svg viewBox="0 0 1350 290"><g stroke="#dce3ed"><path d="M40 30H1320M40 100H1320M40 170H1320M40 240H1320"/></g><path class="trend-line" d="M40 45 220 61 400 75 580 65 760 130 940 157 1120 215 1320 242" stroke="#6654ba" stroke-width="6" fill="none"/><g fill="#485b6e" font-size="21"><text x="40" y="282">Week 31</text><text x="600" y="282">Week 35</text><text x="1220" y="282">Week 38</text></g></svg></div></div></div>`;
const apiBridge=`<div class="api-bridge"><div>${logo}</div><span class="api-path"><i></i><b>API</b></span><div class="api-capability">${glyph('clock')}Freshness</div><div class="api-capability">${glyph('flow')}ETL</div><span class="bridge-arrow">↑</span></div>`;
const home=app('Your data workspace',`<div class="home-tiles">${[['Create a Flow','flow'],['Browse datasets','table'],['Review AI findings','spark']].map(s=>`<div>${glyph(s[1])}<h3>${s[0]}</h3></div>`).join('')}</div><div class="home-flow"><h3>Your Flows</h3><div><b>Monthly sales</b><span>Scheduled</span>${icon('check')}</div><div><b>Stock refresh</b><span>Scheduled</span>${icon('check')}</div></div>`);
const access=`<div class="server-unit">${glyph('server')}<h2>Internal server</h2></div><div class="server-line"><i></i></div><div class="access-browser frame">${chrome('Metronome','metronome.example',home)}</div><div class="access-url">metronome.example</div>`;
const mcp=`<div class="mcp-equation"><div class="ai-input">${aiNames.map((s,i)=>`<div class="ai-brand" data-brand="${i}">${aiLogo(i)}<h2>${s}</h2></div>`).join('')}</div><span class="equation-op">+</span><div class="mcp-hub">${mark}<h2>Metronome</h2><b>MCP</b></div><span class="equation-op">=</span><div class="ai-output"><div class="boost-ring"></div>${aiNames.map((s,i)=>`<div class="ai-brand boosted" data-brand="${i}">${aiLogo(i)}<h2>${s}</h2></div>`).join('')}<div class="power-orbit orbit-data">${glyph('table')}</div><div class="power-orbit orbit-time">${glyph('clock')}</div><div class="power-orbit orbit-flow">${glyph('flow')}</div><div class="boost-spark">${glyph('spark')}</div></div></div>`;
const scene=(id,content)=>`<section class="scene" id="${id}">${content}</section>`;
let html=scene('s1',`<div class="intro-asap frame">${chrome('ASAP — 판매 실적','asap.example/reports',portal())}</div><div class="intro-gscm frame">${chrome('GSCM — 재고 현황','gscm.example/inventory',portal(true))}</div>`);
html+=scene('s2',map);
html+=scene('s3',useData);
html+=scene('s4',`${noCode}<div class="builder-browser frame">${chrome('Metronome — Create a Flow','metronome.example/flows/new',builder)}</div>`);
html+=scene('s5',`<h1 class="feature-title">Overnight agents.</h1><div class="auditor-browser frame">${chrome('Metronome — Local AI agents','metronome.example/ai-auditor',auditor)}</div>`);
html+=scene('s6',`<div class="findings-browser frame">${chrome('Metronome — AI findings','metronome.example/ai-auditor/findings',findings)}</div>`);
html+=scene('s7',`<div class="meto-browser frame">${chrome('METO AI Portal — Gulf operations','meto-ai.example/dashboards/gulf',dashboard)}</div>${apiBridge}`);
html+=scene('s8',access);
html+=scene('s9',mcp);
const scenes=[['s1',0,10,'ASAP & GSCM'],['s2',10,24,'Connected sources'],['s3',24,36,'Excel & your AI tools'],['s4',36,62,'Build a Flow without code'],['s5',62,78,'Overnight local AI agents'],['s6',78,94,'Five findings & a proposed fix'],['s7',94,110,'METO AI Portal'],['s8',110,122,'A website you can access'],['s9',122,144,'Metronome MCP']].map(([id,start,end,name])=>({id,start,end,name}));
const config={duration,scenes,narration};
const css=fs.readFileSync('compositions/film.css','utf8'),runtime=fs.readFileSync('compositions/runtime.js','utf8');
fs.writeFileSync('timeline.json',JSON.stringify({title:'Metronome — Your data, connected',version:3,durationSeconds:duration,width:1920,height:1080,fps:30,...config},null,2)+'\n');
fs.writeFileSync('index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Metronome — Your data, connected</title><style>${css}</style><script src="assets/vendor/gsap.min.js"></script></head><body><main id="film" data-composition-id="metronome-your-data-connected" data-width="1920" data-height="1080" data-duration="${duration}" data-fps="30">${html}<audio id="narration-and-music" src="audio/score.wav" data-start="0" data-duration="${duration}" data-track-index="10"></audio></main><script>window.FILM_CONFIG=${JSON.stringify(config)};${runtime}</script></body></html>`);
fs.writeFileSync('assets/build-data.json',JSON.stringify(config));console.log(`Built ${duration}-second film, ${scenes.length} scenes, no subtitles.`);
