import fs from 'node:fs';
import path from 'node:path';
import {etlSVG,capabilitySVG} from '../compositions/introduction.js';
import {wizardMark,questionsScene,wizardApp,closingScene} from '../compositions/wizard.js';
const base=path.resolve(import.meta.dirname,'..'); process.chdir(base);
const narration=JSON.parse(fs.readFileSync('narration.json','utf8'));
const mark=`<svg viewBox="0 0 32 32" fill="none" aria-label="Metronome"><path d="M10 27h12L19 5h-6l-3 22Z" fill="#e2f1ef" stroke="#0d7377" stroke-width="2"/><path d="m16 8 5 13M8 27h16" stroke="#0d7377" stroke-width="2.2" stroke-linecap="round"/><rect x="17" y="13" width="5" height="4" rx="1" fill="#0d7377"/></svg>`;
const logo=`<span class="logo">${mark}<b>Metronome</b></span>`;
const icon=(name)=>{const paths={back:'M19 12H5m7-7-7 7 7 7',forward:'M5 12h14m-7-7 7 7-7 7',reload:'M20 11a8 8 0 1 0-2 6M20 4v7h-7',tune:'M4 7h3m4 0h9M4 17h9m4 0h3M7 4v6m10 4v6',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z',puzzle:'M4 5h6V3a2 2 0 0 1 4 0v2h6v6h-2a2 2 0 0 0 0 4h2v6h-6v-2a2 2 0 0 0-4 0v2H4v-6h2a2 2 0 0 0 0-4H4Z',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',db:'M4 6c0-5 16-5 16 0s-16 5-16 0Zm0 0v12c0 5 16 5 16 0V6M4 12c0 5 16 5 16 0',check:'m5 12 4 4L19 6'};return `<svg class="i" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${name==='more'?'<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>':`<path d="${paths[name]||paths.db}"/>`}</svg>`};
const favicon=title=>title.startsWith('Metronome')?mark:title.startsWith('Wizard')?wizardMark:`<span class="favicon">${title[0]}</span>`;
function chrome(title,url,body){return `<div class="chrome"><div class="chrome-tabs"><span class="tab-search">⌄</span><div class="chrome-tab">${favicon(title)}<span>${title}</span>${icon('close')}</div><span class="new-tab">${icon('plus')}</span><div class="win-controls"><span>−</span><span>□</span><span>×</span></div></div><div class="chrome-toolbar">${icon('back')}<span class="disabled">${icon('forward')}</span>${icon('reload')}<div class="omnibox">${icon('tune')}<span>${url}</span>${icon('star')}</div>${icon('puzzle')}<span class="chrome-profile">M</span>${icon('more')}</div><div class="browser-content">${body}</div></div>`}

const duration=120;
const cursor=`<svg class="pointer" viewBox="0 0 40 48"><path d="M4 3 33 28 21 30 27 43 20 46 14 32 4 41Z" fill="#fff" stroke="#172d38" stroke-width="2.5"/></svg>`;
const glyph=(name)=>{const paths={website:'M3 4h26v22H3Zm0 6h26M8 7h1m3 0h1',table:'M3 4h26v24H3Zm0 8h26M12 12v16M3 20h26',clock:'M16 3a13 13 0 1 0 0 26 13 13 0 0 0 0-26Zm0 6v8l6 4',server:'M4 3h24v11H4Zm0 15h24v11H4ZM9 8h1m-1 15h1m8-15h5m-5 15h5',mail:'M3 6h26v21H3Zm0 0 13 11L29 6',code:'m11 8-8 8 8 8m10-16 8 8-8 8M18 3l-4 26',flow:'M4 12h8v8H4Zm16 0h8v8h-8ZM12 16h8M16 16V4h8'};return `<svg class="glyph" viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round" stroke-linecap="round"><path d="${paths[name]||paths.table}"/></svg>`};
function app(title,body,active='Flows'){return `<div class="app"><nav class="appnav">${logo}<div>${['Flows','Database','AI Auditor'].map(n=>`<span class="${n===active?'active':''}">${n}</span>`).join('')}</div><span class="avatar">M</span></nav><div class="app-body"><h2>${title}</h2>${body}</div></div>`}
const markets=['중동 전체','아랍에미리트','사우디아라비아','쿠웨이트','카타르','오만','바레인'];
const values=[['49,650','46,300','52,150','▲ 5.0%','▲ 12.6%'],['12,480','11,260','14,030','▲ 12.4%','▲ 24.6%'],['18,260','18,510','17,960','▼ 1.6%','▼ 3.0%'],['4,680','4,510','4,970','▲ 6.2%','▲ 10.2%'],['3,240','2,980','3,460','▲ 6.8%','▲ 16.1%'],['2,850','2,630','2,910','▲ 2.1%','▲ 10.6%'],['2,140','1,980','2,270','▲ 6.1%','▲ 14.6%']];
function reportTable(gscm){return `<table class="report-table"><thead><tr><th rowspan="2">${gscm?'판매 법인':'지역 / 국가'}</th><th colspan="3">${gscm?'재고 수량':'판매 실적'}</th><th colspan="2">증감률</th></tr><tr><th>2025년 9월</th><th>2026년 8월</th><th>2026년 9월</th><th>전년비 (YoY)</th><th>전월비</th></tr></thead><tbody>${markets.map((m,i)=>`<tr class="report-row ${i===0?'total':''}"><th>${m}</th>${values[i].map((v,j)=>`<td class="${j>2?(v.includes('▲')?'up':'down'):''}">${gscm&&j<3?(Math.round(Number(v.replaceAll(',',''))*.68)).toLocaleString('en-US'):v}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function portal(gscm=false){return `<div class="report-portal ${gscm?'gscm':'asap'}"><div class="portal-top"><b>${gscm?'GSCM':'ASAP'}</b><nav>${gscm?'공급 계획　　재고 현황　　출하 관리':'경영정보　　판매분석　　정기보고서　　다운로드'}</nav><span>홍길동 ▾</span></div><div class="portal-layout">${gscm?'<aside><b>공급망 관리</b><span>재고 현황</span><span>입출고 조회</span><span>월별 실적</span><span>내보내기</span></aside>':''}<div class="portal-main"><h2>${gscm?'법인별 재고 현황':'국가별 판매 실적 조회'}</h2><div class="portal-filter"><span>조회기간 <b>2026년 9월 ▾</b></span><span>지역 <b>중동 ▾</b></span><button>조회</button></div><div class="table-actions"><span>${gscm?'재고 현황':'판매 실적'}</span><button>↓ 다운로드</button></div>${reportTable(gscm)}</div></div></div>`}
const sources=['ASAP','GSCM','Bigdata portal','Datahub','NERP','Email reports'];
// Metronome loads the PostgreSQL tables that Wizard later queries read-only.
const datasetNames=['Sell-in','Sell-out','Stock','Shipments'];
const map=`<div class="flow-map"><svg class="map-links" viewBox="0 0 1720 680"><g fill="none" stroke="#c9d5d6" stroke-width="2.5">${sources.map((_,i)=>`<path d="M370 ${75+i*106}C560 ${75+i*106} 540 340 700 340"/>`).join('')}<path d="M1020 340H1250"/></g><g class="flow-dashes" fill="none" stroke="#0d7377" stroke-width="5" stroke-linecap="round" stroke-dasharray="8 74">${sources.map((_,i)=>`<path d="M370 ${75+i*106}C560 ${75+i*106} 540 340 700 340"/>`).join('')}<path d="M1020 340H1250"/></g><path d="m1236 330 15 10-15 10" fill="none" stroke="#0d7377" stroke-width="3"/></svg><div class="source-column">${sources.map((s,i)=>`<div class="source-item" data-source="${i}"><span class="source-icon">${i===5?glyph('mail'):glyph(i===3?'server':'website')}</span><b>${s}</b></div>`).join('')}</div><div class="hub">${mark}<h2>Metronome</h2></div><div class="database"><h2>${icon('db')}PostgreSQL</h2>${datasetNames.map((s,i)=>`<div class="dataset" data-dataset="${i}">${glyph('table')}<b>${s}</b>${icon('check')}</div>`).join('')}</div></div>`;
const reportNames=['Daily sales summary','Weekly sales summary','Inventory snapshot','Stock aging report','Monthly sales report','Order status','Shipment tracking','Purchase orders','Returns analysis','Revenue by region','Forecast vs actual','Customer activity'];
const destinations=['Shared drive','Email','PostgreSQL'];
const schedules=['Every day · 06:00','Every weekday · 06:00','Every Monday · 08:00','First day of month · 09:00'];
const choiceField=(key,label,g,placeholder,options,up=false)=>`<div class="build-field choice-field" data-field="${key}"><div>${glyph(g)}<label id="${key}-label">${label}</label></div><button class="field-trigger" data-dropdown="${key}" role="combobox" aria-labelledby="${key}-label" aria-expanded="false" aria-controls="${key}-options"><span>${placeholder}</span><em>⌄</em></button><div id="${key}-options" class="field-menu ${up?'opens-up':''}" role="listbox" aria-labelledby="${key}-label" hidden><div class="menu-options">${options.map((name,i)=>`<button ${key==='data'&&i>=8?'data-layout-allow-overflow':''} role="option" aria-selected="false" data-option="${key}" data-option-index="${i}" data-value="${name}">${glyph(g)}<span>${name}</span><i>✓</i></button>`).join('')}</div>${key==='data'?'<div class="menu-footer">12 reports available</div>':''}</div></div>`;
const builder=app('Create your Flow',`<div class="builder-workspace"><div class="build-inputs"><div class="build-field website-field" data-field="website"><div>${glyph('website')}<label for="flow-website">Website</label></div><input id="flow-website" type="text" autocomplete="off" spellcheck="false" placeholder="Enter a website address"><span class="typing-caret"></span></div>${choiceField('data','Data','table','Choose a report',reportNames)}${choiceField('destination','Destination','server','Choose a destination',destinations)}${choiceField('schedule','Schedule','clock','Choose when to run',schedules,true)}</div><div class="pipeline-canvas"><div class="pipeline-empty">${glyph('flow')}</div><div class="pipeline-nodes">${[['Collect','website'],['Transform','table'],['Load','server'],['Repeat','clock']].map((s,i)=>`<div class="pipeline-node" data-node="${i}">${glyph(s[1])}<b>${s[0]}</b></div>`).join('<span class="node-link">→</span>')}</div><div class="pipeline-status">${icon('check')}Your Flow is ready</div></div></div><button class="create-flow" disabled>Create Flow</button><div class="flow-cursor">${cursor}<i></i></div>`);
const noCode=`<div class="code-race"><div class="code-editor"><div class="editor-tabs">${glyph('code')}<b>report.py</b><span>×</span></div><div class="editor-code"><div class="line-numbers">1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10</div><pre id="slow-code"></pre><i class="code-caret"></i></div><div class="editor-status">Python <span>Writing script…</span></div></div></div>`;
// Word-boundary cues come from audio/score.py; before the first voice pass, each cue falls back to its segment start.
const cueFile='assets/cues.json';
const cues=fs.existsSync(cueFile)?JSON.parse(fs.readFileSync(cueFile,'utf8')).cues:{};
for(const segment of narration)for(const key of Object.keys(segment.cues||{}))if(!(key in cues)){cues[key]=segment.start;console.warn(`Cue ${key} has no voice timing yet; using its segment start.`)}
const scene=(id,content,cls='')=>`<section class="scene ${cls}" id="${id}">${content}</section>`;
let html=scene('s1',`<div class="intro-asap frame">${chrome('ASAP — 판매 실적','asap-portal.com/reports',portal())}</div><div class="intro-gscm frame">${chrome('GSCM — 재고 현황','gscm.example/inventory',portal(true))}</div>`);
html+=scene('sETL',`<div class="etl-scene">${etlSVG(9,cues)}</div>`);
html+=scene('s2',`${map}<div class="pipeline-controls">${capabilitySVG(20,cues)}</div>`);
html+=scene('s4',`<div class="comparison-heading code-way"><h2>Without Metronome</h2><p>Write code</p></div><div class="comparison-heading flow-way"><h2>With Metronome</h2><p>No code</p></div><div class="comparison-divider"></div>${noCode}<div class="builder-browser frame">${chrome('Metronome — Create a Flow','metronome.example/flows/new',builder)}</div>`);
html+=scene('sQ',questionsScene());
html+=scene('sWiz',`<div class="wizard-browser frame">${chrome('Wizard','wizard.example',wizardApp(cursor))}</div><div class="fed-callout">${mark}<span>Loaded by <b>Metronome</b> · refreshed 06:00</span></div>`,'wizard-scene');
html+=scene('sEnd',closingScene(mark));
const scenes=[['s1',0,9,'Where reports start'],['sETL',9,20,'The work behind reporting'],['s2',20,31,'Meet Metronome'],['s4',31,47,'Build a Flow without code'],['sQ',47,57,'Questions that cross systems'],['sWiz',57,101.5,'Meet Wizard: ask, trace, check'],['sEnd',101.5,120,'Metronome + Wizard']].map(([id,start,end,name])=>({id,start,end,name}));
const config={duration,scenes,narration,cues};
const builderRuntime=fs.readFileSync('compositions/builder.js','utf8');
const introRuntime=fs.readFileSync('compositions/introduction.js','utf8').replaceAll('export function','function');
const css=fs.readFileSync('compositions/film.css','utf8')+fs.readFileSync('compositions/wizard.css','utf8'),runtime=fs.readFileSync('compositions/runtime.js','utf8');
const title='Metronome + Wizard — From portal to decision';
fs.writeFileSync('builder-demo.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Metronome — Try the Flow builder</title><style>${css}body{overflow:hidden}#film{transform:scale(var(--demo-scale,1));transform-origin:top left}.manual-demo .scene{visibility:visible;opacity:1}</style></head><body class="manual-demo"><main id="film"><section class="scene" id="s4"><div class="builder-browser frame">${chrome('Metronome — Create your Flow','metronome.example/flows/new',builder)}</div></section></main><script>${builderRuntime}window.FilmBuilder.draw(0);const fit=()=>document.documentElement.style.setProperty('--demo-scale',String(Math.min(innerWidth/1920,innerHeight/1080)));addEventListener('resize',fit);fit();</script></body></html>`);
fs.writeFileSync('timeline.json',JSON.stringify({title,version:11,durationSeconds:duration,width:1920,height:1080,fps:30,...config},null,2)+'\n');
fs.writeFileSync('index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${title}</title><style>${css}</style><script src="assets/vendor/gsap.min.js"></script></head><body><main id="film" data-composition-id="metronome-your-data-connected" data-width="1920" data-height="1080" data-duration="${duration}" data-fps="30">${html}<audio id="narration-and-music" src="audio/score.wav" data-start="0" data-duration="${duration}" data-track-index="10"></audio></main><script>window.FILM_CONFIG=${JSON.stringify(config)};${introRuntime}${builderRuntime}${runtime}</script></body></html>`);
fs.writeFileSync('assets/build-data.json',JSON.stringify(config));console.log(`Built ${duration}-second film, ${scenes.length} scenes, no subtitles.`);
