import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';

const base = path.resolve(import.meta.dirname, '..');
process.chdir(base);
const t = JSON.parse(fs.readFileSync('timeline.json', 'utf8'));
const sec = b => b * 60 / t.bpm;
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const mark = (cls='') => `<svg class="mark ${cls}" viewBox="0 0 24 24" aria-label="Metronome"><path d="M7.5 21h9L14.6 4.5H9.4L7.5 21Z" fill="#5EEAD4" fill-opacity=".07" stroke="#5EEAD4" stroke-width="1.6"/><g class="mark-arm"><path d="M12 6.2l3.2 10.2" stroke="#E5E3DD" stroke-width="1.5" stroke-linecap="round"/><circle cx="14" cy="12.4" r="1.7" fill="#5EEAD4"/></g><path d="M6 21h12" stroke="#E5E3DD" stroke-width="1.5"/></svg>`;
const chrome = (name,body,cls='') => `<div class="window ${cls}"><div class="windowbar"><div class="brand">${mark()}<b>Metronome</b></div><span>${name}</span><span class="sample">Illustrative data</span></div>${body}</div>`;
const steps = ['Open ASAP report','Set period · Last week','Run report','Download Excel'];
const sources = [
  ['ASAP','Daily sell-out','UAE units','12,480','23:40'],
  ['GSCM','Weekly stock cover','Gulf cover','4.2 wks','02:00'],
  ['Big Data Portal','Channel inventory','Available units','24,960','02:05'],
  ['Data Hub','Price tracker','Price feed','6,240 rows','02:07']
];
const sourceCard = (s,i) => `<div class="system sys${i+1}"><div class="source-top"><span class="source-dot"></span><small>DATA SOURCE</small><span class="source-refresh">↻ ${s[4]}</span></div><b>${s[0]}</b><span class="source-subtitle">${s[1]}</span><div class="source-record"><span>${s[2]}</span><strong>${s[3]}</strong></div></div>`;
const pipelineSteps = [
  ['Record task','ASAP report actions'],
  ['Schedule','Every night · 02:00'],
  ['Gather','ASAP + GSCM + 2'],
  ['Check','Freshness and row counts'],
  ['AI ready','Evidence for agents']
];
const pipeline = `<div class="pipeline-stage"><div class="pipeline-heading"><div class="eyebrow">METRONOME · AUTOMATIONS</div><h2>Automation pipeline</h2><p>Build once. See every part.</p></div><div class="pipeline-flow">${pipelineSteps.map((s,i)=>`<div class="pipeline-node" data-pipeline="${i}"><small>0${i+1}</small><b>${s[0]}</b><span>${s[1]}</span><i></i></div>`).join('<div class="pipeline-arrow">→</div>')}</div><div class="pipeline-inspector"><div><small>SELECTED STEP</small><b class="inspector-name">Record task</b><span class="inspector-detail">ASAP report actions captured</span></div><div class="inspector-status"><span class="success-dot"></span><b>Visible in the run</b><small>Open any stage to inspect its input, action and result</small></div></div></div>`;
const chart = `<svg class="chart" viewBox="0 0 1100 220"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#5EEAD4" stop-opacity=".18"/><stop offset="1" stop-color="#5EEAD4" stop-opacity="0"/></linearGradient></defs><path d="M0 180H1100M0 110H1100M0 40H1100" stroke="#3D3B37" stroke-width="1"/><path d="M0 45L150 55L315 72L470 62L630 100L780 120L950 154L1100 178V220H0Z" fill="url(#chart-fill)"/><path class="chart-line" d="M0 45L150 55L315 72L470 62L630 100L780 120L950 154L1100 178" fill="none" stroke="#5EEAD4" stroke-width="4"/><circle cx="1100" cy="178" r="7" fill="#5EEAD4"/></svg>`;
const report = `<div class="reportbody"><div class="reporttitle"><div><div class="eyebrow">WEEKLY OVERVIEW</div><h2>Gulf stock cover · Week 38</h2></div><span class="pill">GSCM + ASAP</span></div><div class="kpis"><div><label>Stock cover</label><strong>4.2 <small>wks</small></strong><em>▼ 0.8 wks</em></div><div><label>UAE sell-out</label><strong>▲12<span>%</span></strong><em class="positive">Week on week</em></div><div><label>Inbound delayed</label><strong>2 <small>shipments</small></strong><em>Six days behind</em></div></div>${chart}<div class="chartlabels"><span>Week 31</span><span>Week 38</span></div><div class="insight">Cover fell because UAE sell-out rose 12% while two inbound shipments slipped six days.</div><div class="sources">Sources: GSCM shipments · ASAP sell-out</div></div>`;
const roleMini = `<div class="screen-ui"><div class="mini-brand">${mark()}<b>Metronome</b></div><h3>Gulf performance</h3><div class="mini-kpis"><div><span>Sell-out</span><b>+12%</b></div><div><span>Stock cover</span><b>4.2 wks</b></div></div>${chart.replaceAll('chart-fill','mini-fill')}<p>Weekly summary · Illustrative</p></div>`;

const roleReports=[['Stock cover','Cover','4.2 wks','Change','−0.8 wks'],['Margin overview','Margin','18.4%','Change','+1.2 pts'],['Weekly sell-out','Sell-out','+12%','Units','12,480'],['Inbound tracker','Arriving','8 loads','Delayed','2 loads']];
const manualFlow = `<div class="manual-flow"><div class="manual-eyebrow">BEFORE METRONOME · MANUAL HANDOFFS</div><div class="manual-steps">${[['Export','ASAP file'],['Copy','Into a workbook'],['Paste','Across teams'],['Email','The report']].map((s,i)=>`<div class="manual-step" data-manual="${i}"><small>0${i+1}</small><b>${s[0]}</b><span>${s[1]}</span></div>`).join('<div class="manual-arrow">→</div>')}</div><div class="manual-note">Four handoffs. One answer still waiting.</div></div>`;
const nightIllustration = `<svg class="night-illustration" viewBox="0 0 860 520" aria-hidden="true"><path d="M0 455H860" stroke="#48675d" stroke-width="3"/><rect x="125" y="215" width="120" height="240" rx="4" fill="#1a312d"/><rect x="260" y="155" width="160" height="300" rx="4" fill="#23413b"/><rect x="435" y="245" width="115" height="210" rx="4" fill="#1c3631"/><rect x="565" y="105" width="128" height="350" rx="4" fill="#284c43"/><path d="M628 105V35" stroke="#456d61" stroke-width="4"/><rect x="705" y="282" width="100" height="173" rx="4" fill="#1b3731"/><g fill="#d6d8c4">${[[155,255],[205,255],[155,310],[205,310],[155,365],[205,365],[305,205],[365,205],[305,260],[365,260],[305,315],[365,315],[305,370],[365,370],[470,290],[510,290],[470,345],[510,345],[605,150],[655,150],[605,205],[655,205],[605,260],[655,260],[605,315],[655,315],[740,325],[780,325],[740,380],[780,380]].map(([x,y])=>`<rect x="${x}" y="${y}" width="10" height="13" rx="2" opacity=".58"/>`).join('')}</g><circle cx="762" cy="80" r="28" fill="#f4efe6" opacity=".78"/></svg>`;
const roleSymbols=[
  '<path d="M30 17V44M46 17V44M17 30H59M17 17H59V59H17Z"/>',
  '<path d="M17 59H59M24 51V36M37 51V24M50 51V17"/>',
  '<path d="M17 51L31 39L41 44L58 20M46 20H58V32"/>',
  '<rect x="16" y="30" width="18" height="18"/><rect x="35" y="30" width="18" height="18"/><rect x="25" y="11" width="18" height="18"/>'
];
const roleIllustration=(r,i)=>`<div class="role-art"><svg viewBox="0 0 660 560" aria-hidden="true"><circle cx="286" cy="293" r="230" fill="#17302c" opacity=".55"/><path d="M55 454H610" stroke="#547568" stroke-width="5"/><path d="M95 455V533M565 455V533" stroke="#496659" stroke-width="8"/><rect x="286" y="321" width="230" height="130" rx="10" fill="#2c4941" stroke="#759182" stroke-width="3"/><path d="M302 439H500" stroke="#b3c4b4" stroke-width="5"/><circle cx="185" cy="232" r="62" fill="#c6c5b4"/><path d="M107 444C107 349 115 315 170 308C232 300 274 345 276 444Z" fill="#356359"/><path d="M233 350C270 368 286 390 318 400" fill="none" stroke="#c6c5b4" stroke-width="24" stroke-linecap="round"/><rect x="326" y="350" width="124" height="72" rx="7" fill="#171f1d" stroke="#6a9282" stroke-width="3"/><g transform="translate(470 115)" fill="none" stroke="#a9dbcb" stroke-width="5" stroke-linejoin="round" stroke-linecap="round">${roleSymbols[i]}</g></svg><div class="role-art-label">${r.toUpperCase()} · WORKSPACE</div></div>`;
const roleContent=i=>{
  const r=roleReports[i];
  let out=roleMini.replace('Gulf performance',r[0]).replace(/<div class="mini-kpis">[\s\S]*?<\/div><\/div>/,`<div class="mini-kpis"><div><span>${r[1]}</span><b>${r[2]}</b></div><div><span>${r[3]}</span><b>${r[4]}</b></div></div>`);
  if(i===1||i===2)out=out.replaceAll('M0 45L150 55L315 72L470 62L630 100L780 120L950 154L1100 178','M0 178L150 161L315 168L470 125L630 116L780 75L950 68L1100 35').replace('cy="178"','cy="35"');
  const labels=['Stock cover, weeks','Gross margin, percent','Sell-out, units','Inbound shipments'];
  return out.replace('Weekly summary · Illustrative',labels[i]+' · Illustrative');
};
const scenes = {
s1:`<canvas class="three" id="s1-three" data-layout-ignore></canvas><div class="intro-sources"><div>ASAP <span>sell-out</span></div><div>GSCM <span>stock cover</span></div><div>Big Data Portal <span>inventory</span></div><div>Data Hub <span>prices</span></div></div><div class="edge-shade" data-layout-ignore></div>`,
s2:`<div class="source-field" data-layout-ignore></div><div class="constellation">${sources.map(sourceCard).join('')}<div class="more">+26 <span>more sources</span></div><svg class="links" viewBox="0 0 1920 1080" data-layout-ignore><path d="M318 594L731 789L1180 560L1600 772M318 594L1600 772M731 789L1180 560"/></svg></div>${manualFlow}`,
s3:`<div class="turn-symbol"><div class="ripple r1"></div><div class="ripple r2"></div>${mark('hero-mark')}<span>Metronome</span></div><div class="sync-systems"><div class="sync-system sync-asap">ASAP<span>Sell-out data</span></div><div class="sync-system sync-gscm">GSCM<span>Stock-cover data</span></div><div class="sync-system sync-portal">Big Data Portal<span>Inventory data</span></div><div class="sync-system sync-hub">Data Hub<span>Price data</span></div></div><svg class="sync-links" viewBox="0 0 1920 1080" data-layout-ignore><path d="M470 445L800 460M580 670L810 580M1450 430L1110 460M1370 680L1100 580"/></svg>`,
s4:`<div class="record-stage"><div class="portal"><div class="portalbar"><span class="portal-dots">● ● ●</span><b>ASAP</b><span>Illustrative portal</span></div><div class="portalbody"><div class="eyebrow">REPORTS</div><h2>Weekly sell-out</h2><p>Choose a period, then run your report.</p><div class="formlabel">Reporting period</div><div class="select">Last week <span>⌄</span></div><div class="portal-actions"><span class="run-button">Run report</span><span class="download-button">Download Excel</span></div><div class="portal-table"><div>Region <span>Units</span></div><div>Gulf <span>12,480</span></div><div>Levant <span>8,320</span></div></div></div><svg class="cursor" viewBox="0 0 36 48"><path d="M3 2L3 36L12 28L20 45L27 42L19 26L32 25Z" fill="#E5E3DD" stroke="#07080C" stroke-width="2"/></svg></div>${chrome('Recording editor',`<div class="editorbody"><div class="editorheading"><h2>Weekly sell-out</h2><span class="pill">Recorded</span></div><div class="step-list">${steps.map((s,i)=>`<div class="step" data-step="${i}"><span class="step-num">${String(i+1).padStart(2,'0')}</span><span>${s}</span><span class="step-check">✓</span></div>`).join('')}</div><div class="editorfoot"><span class="success-dot"></span><span>Ready to run</span><span>4 steps</span></div></div>`,'editor')}</div>${pipeline}<div class="night"><div class="night-panel"><div class="eyebrow">SCHEDULED AUTOMATION</div><div class="night-time">02:00 <span>· Dubai</span></div><p>Four sources, ready for the morning.</p><div class="night-status"><span>ASAP</span><span>GSCM</span><span>Big Data Portal</span><span>Data Hub</span></div></div>${nightIllustration}</div>`,
s5:`<div class="data-backdrop"><div class="data-caption">METRONOME · CONNECTED RUNS</div><div class="data-lines"><i></i><i></i><i></i><i></i></div></div><div class="run-lane"><span>RECORD</span><i></i><span>SCHEDULE</span><i></i><span>GATHER</span><i></i><span>CHECK</span><i></i><span>AI READY</span></div>${chrome('Run history',`<div class="historybody"><div class="historyheading"><h2>While the city sleeps.</h2><span class="pill">All runs complete</span></div><table><thead><tr><th>Flow</th><th>Status</th><th>Rows</th><th>Started</th></tr></thead><tbody>${[['GSCM','Weekly stock cover','12,480','02:00'],['ASAP','Daily sell-out','8,320','02:02'],['Big Data Portal','Channel inventory','24,960','02:05'],['Data Hub','Price tracker','6,240','02:07']].map((r,i)=>`<tr data-row="${i}"><td><b>${r[0]}</b><span> · ${r[1]}</span></td><td class="success">● Success</td><td class="rows-count">${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div>`,'history')}`,
s6:`<div class="ai-context">Concept preview <span>· Illustrative data</span></div><div class="ask"><div class="ask-label">ASK METRONOME · AI AGENTS</div><div class="question">Why did Gulf stock cover drop last week?</div><div class="ask-bottom"><span class="pill">GSCM</span><span class="pill">ASAP</span><span class="ask-arrow">↗</span></div></div><div class="agent-investigation"><div class="agent-head"><div><small>METRONOME · AUTOMATION OUTPUTS</small><h2>AI agents investigate</h2></div><span class="pill">Evidence connected</span></div><div class="agent-evidence"><div><small>ASAP · SELL-OUT</small><b>UAE demand rose 12%</b><span>Compare weekly trend</span></div><div><small>GSCM · SHIPMENTS</small><b>2 inbound shipments late</b><span>Check delivery dates</span></div><div><small>GSCM · STOCK</small><b>Cover fell 0.8 weeks</b><span>Reconcile stock position</span></div></div><div class="agent-outcome"><span class="agent-arrow">→</span><div><b>Metronome boosts AI agents</b><span>Connected evidence becomes a sourced insight and report.</span></div></div></div>${chrome('Reports',report,'report')}<div class="email">${mark()}<h2>Your morning, ready.</h2><div class="email-paper"><b>Gulf stock cover · Week 38</b><span>Weekly report</span></div><div class="avatars">${['JK','MS','AL','SY','RK','+9'].map(s=>`<span>${s}</span>`).join('')}</div><p>Sent to 14 people · 07:00</p></div><div class="audit"><div class="audit-top">02:00 <span>· Nightly AI audit</span></div><div class="attention-label">Attention</div><h2>Data Hub price feed arrived 38% short.</h2><p>Downstream refresh paused.</p><div class="audit-footer">Review the feed before continuing</div></div>`,
s7:`${['planner','finance','sales','logistics'].map((r,i)=>`<div class="role-photo role-${r}" data-role="${i}">${roleIllustration(r,i)}<div class="role-screen">${roleContent(i).replaceAll('mini-fill',`mini-fill-${r}`)}</div><div class="role-name">${r[0].toUpperCase()+r.slice(1)}</div></div>`).join('')}`,
s8:`<div class="end-arm">${mark('end-mark')}</div><div class="lockup">${mark()}<span>Metronome</span></div><div class="end-glow" data-layout-ignore></div>`
};

const fontCSS = [300,400,500,600,700,800].map(w=>`@font-face{font-family:Outfit;font-style:normal;font-weight:${w};src:url('assets/fonts/outfit-${w}.ttf') format('truetype')}`).join('\n');
const css=fontCSS+'\n'+fs.readFileSync('compositions/film.css','utf8');
for(const s of t.scenes){
const supers=t.supers.filter(x=>x.scene===s.id).map(x=>`<div id="${x.id}" class="super ${x.id.includes('kinetic')?'kinetic-super':''} ${x.id.includes('disclosure')?'disclosure':''}" data-super="${x.id}">${esc(x.text)}</div>`).join('');
const body=`<style>#${s.id}-root{position:absolute;inset:0;width:100%;height:100%;overflow:hidden;background:#07080C}</style><div id="${s.id}-root" data-composition-id="${s.id}" data-width="1920" data-height="1080" data-duration="${sec(s.endBeat-s.startBeat)}"><div class="scene scene-${s.id}" id="${s.id}-scene">${scenes[s.id]}${supers}</div></div>`;
const script=`const tl=gsap.timeline({paused:true}); const clock={t:${sec(s.startBeat)}}; window.Film.mount('${s.id}'); tl.to(clock,{t:${sec(s.endBeat)},duration:${sec(s.endBeat-s.startBeat)},ease:'none',onUpdate:()=>window.Film.draw('${s.id}',clock.t)},0); window.__timelines['${s.id}']=tl;`;
fs.writeFileSync(s.file,`<!doctype html><html><head><meta charset="UTF-8"></head><body><template>${body}<script>{${script}}</script></template></body></html>`);
}
const hosts=t.scenes.map(s=>`<div class="clip" id="${s.id}" data-composition-id="${s.id}" data-composition-src="${s.file}" data-start="${sec(s.startBeat)}" data-duration="${sec(s.endBeat-s.startBeat)}" data-track-index="1" data-width="1920" data-height="1080"></div>`).join('\n');
fs.writeFileSync('index.html',`<!doctype html><html><head><meta charset="UTF-8"><title>Metronome — In Sync</title><style>${css}</style><script src="assets/vendor/gsap.min.js"></script><script src="assets/film-runtime.js"></script></head><body><div id="film" data-composition-id="metronome-in-sync" data-width="1920" data-height="1080" data-duration="${sec(t.durationBeats)}">${hosts}<div class="camera-bridge" data-layout-ignore></div><audio id="score" src="audio/score.wav" data-start="0" data-duration="${sec(t.durationBeats)}" data-track-index="10"></audio></div><script>{const tl=gsap.timeline({paused:true});const clock={t:0};tl.to(clock,{t:${sec(t.durationBeats)},duration:${sec(t.durationBeats)},ease:'none',onUpdate:()=>window.Film.bridge(clock.t)},0);window.__timelines['metronome-in-sync']=tl;window.addEventListener('hf-seek',e=>window.Film.seek(e.detail.time));}</script></body></html>`);
fs.writeFileSync('assets/build-data.json',JSON.stringify({timeline:t}));
await build({entryPoints:['compositions/runtime.js'],outfile:'assets/film-runtime.js',bundle:true,format:'iife',globalName:'FilmRuntime',minify:false,logLevel:'warning'});
console.log(`Built ${t.scenes.length} sub-compositions; ${t.supers.length} supers; ${sec(t.durationBeats)} seconds. Timing source: timeline.json`);
