table Survey_Responses
	lineageTag: c8c97781-31fb-4ce1-865e-e5794fdab6db

	column response_id
		dataType: string
		lineageTag: 9dc5f8b6-a54b-46c2-b1ee-8b07ff4861c8
		summarizeBy: none
		sourceColumn: response_id

	column customer_id
		dataType: string
		lineageTag: 8f96c6ac-5d96-4052-8963-978e0ddd1e86
		summarizeBy: none
		sourceColumn: customer_id

	column score
		dataType: int64
		lineageTag: 79fb2008-155a-4183-81b3-a768541c8f84
		summarizeBy: sum
		sourceColumn: score

	column comment
		dataType: string
		lineageTag: 550c9f93-4ab4-4d9f-a495-9227d47c7590
		summarizeBy: none
		sourceColumn: comment

	partition Survey_Responses = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\CRM\survey_responses.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
