table Customer_NPS
	lineageTag: 018ed00c-c877-428e-ba75-d4963f366733

	column quarter
		dataType: string
		lineageTag: 31474fa7-f8f8-423f-a311-53f6313674e0
		summarizeBy: none
		sourceColumn: quarter

	column segment
		dataType: string
		lineageTag: e884ed0e-ae9c-4968-80ae-3941ad541d28
		summarizeBy: none
		sourceColumn: segment

	column nps_score
		dataType: decimal
		lineageTag: 0eb930f7-ed7b-47e5-a62a-f0d667c0d082
		summarizeBy: sum
		sourceColumn: nps_score

	column responses
		dataType: int64
		lineageTag: ed035505-dada-49e9-b079-36639663bc12
		summarizeBy: sum
		sourceColumn: responses

	partition Customer_NPS = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Executive\customer_nps.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
