table Headcount
	lineageTag: d54d97e6-eda5-4a57-bec6-6e5046aa6c70

	column department
		dataType: string
		lineageTag: d62ce9db-ce78-4426-b951-e76ef2037d09
		summarizeBy: none
		sourceColumn: department

	column headcount
		dataType: int64
		lineageTag: c1bb2670-028f-41f0-ade9-717540a23adb
		summarizeBy: sum
		sourceColumn: headcount

	column budget_hc
		dataType: int64
		lineageTag: e92ee417-670e-4b23-90c3-bb0a84b022a8
		summarizeBy: sum
		sourceColumn: budget_hc

	column date
		dataType: string
		lineageTag: 1d302556-47d7-4b49-b7a1-58b1e1b9b9b4
		summarizeBy: none
		sourceColumn: date

	partition Headcount = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Data\Executive\headcount.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table
